### ISSUE TITLE
Can't install joomla on windows

### ISSUE THREAD

**Issue by compojoom** [joomla-extensions/weblinks#100]
The system test fails to install joomla on my Windows machine. The test fails to find the next button on the page with the language select.

I see that in the test we have this
```
 // Select a random language to force reloading of the lang strings after selecting English
$I->selectOptionInChosen('#jform_language', 'Danish (DK)');
$I->selectOptionInChosen('#jform_language', 'English (United Kingdom)');
```

In my case I end up with danish, instead of english. Tried with waiting 2 sec between the selection, but this didn't help either. The only way to go around this is to just select english. 

I'm also not sure that I understand the logic of the comment? Force reloading of the lang strings? The default language is english? Why do we need to reload it?

**Comment by compojoom** [comment]
I think that I've posted this in the wrong repository. I've posted in joomla-browser over here:
https://github.com/joomla-projects/joomla-browser/issues/70

Closing this issue as it is not directly a weblinks issue.

**Comment by zero-24** [comment]
:) No Problem.
