### ISSUE TITLE
Allow using PHP 7 in travis build

### ISSUE THREAD

**Issue by javigomez** [joomla-extensions/weblinks#114]
@jatitoam I'm leaving this one for you for when you have time. No rushes.

https://github.com/joomla-extensions/weblinks/pull/113

The task would be to make it work the PHP7

But we are probably moving to Docker before that so, maybe we don't need to lose time on it.

**Comment by jatitoam** [comment]
yeah, I would go for Docker for this one, but can you also assign it to me so I won't forget the topic?

**Comment by 810** [comment]
any update about this?

**Comment by chrisdavenport** [comment]
Any reason not to add PHP7 to the Travis build at this time? @javigomez @jatitoam

**Comment by yvesh** [comment]
@chrisdavenport It's already in the .travis.yml, but there are some Travis related issues. @810 tried to get it working on JAB, but it is still failing.

**Comment by yvesh** [comment]
Done with #250 // Closed :-)
