### ISSUE TITLE
Review robo file Rewrite rule modification of .htaccess

### ISSUE THREAD

**Issue by javigomez** [joomla-extensions/weblinks#120]
These lines https://github.com/joomla-extensions/weblinks/commit/92fff6966da8918e9c40e8a92d152d30350b65c3#diff-02040fb06a55970e37b936f43e1b859dR193 were created for travis but they are not taking into account the options added in robo file like: $this->cmsPath

@jatitoam I'm creating this issue in case you can have a look. 

Not in a hurry because is only used by travis.

**Comment by jatitoam** [comment]
definitely it needs a fix
any chance you can assign me the issue so I can just filter my assigned tasks later?

**Comment by chrisdavenport** [comment]
Closing for the time being.  Please re-open if you think this is still relevant.  Thanks @javigomez @jatitoam
