### ISSUE TITLE
Fix the name of the buildGitCloneCommand Robo function

### ISSUE THREAD

**Issue by javigomez** [joomla-extensions/weblinks#122]
see: https://github.com/joomla-extensions/weblinks/pull/117/files#r43507247

**Comment by therunnergit** [comment]
@javigomez what do you mean by "fix"? Is it too long? Is it not clear? Because that's exactly what the method does, i.e. build the "git clone" command full string.

**Comment by chrisdavenport** [comment]
Closing for the time being.  Please re-open if you think it is still relevant.  Thanks @javigomez
