### ISSUE TITLE
Robo create:testing-site Fails on Ubuntu 

### ISSUE THREAD

**Issue by puneet0191** [joomla-extensions/weblinks#129]
after the recent changes to create:testing-site function in RoboFile.php, I am not able to use this function,  but previously I was able to use this function on my machine without any issues, but now it seems to throw an  error. I am attaching a screenshot of the error with this. 

![image](https://cloud.githubusercontent.com/assets/3048593/10862713/9210338e-7fda-11e5-977f-f1190b0c3348.png)

**Comment by therunnergit** [comment]
@puneet0191 this should be fixed by #133

**Comment by puneet0191** [comment]
Yeap, fixes the issue. Thanks :+1: 
https://github.com/joomla-extensions/weblinks/pull/133
