### ISSUE TITLE
Edit button visible when there are no categories

### ISSUE THREAD

**Issue by roland-d** [joomla-extensions/weblinks#13]
When there are no categories the New button is not shown because there are no categories. However the other buttons are shown even when there are no entries. These buttons are useless as well since there are no entries nor new entries can be created.

**Comment by therunnergit** [comment]
That happens because the check on the "New" button is not actually on the existing categories, but on the number of categories you have **write access to**. So there may be a situation when you cannot create a new item but have existing items to edit.

My suggestion is to leave it as it is.

**Comment by chrisdavenport** [comment]
Closing for now.  Please re-open if you think this is still an issue.  Thanks everyone.
