### ISSUE TITLE
Add tests for different resolutions

### ISSUE THREAD

**Issue by therunnergit** [joomla-extensions/weblinks#143]
We assume the component should work fine at all the following resolutions:

* 1024x768px (*desktop*)
* 768x1024 (*tablet*)
* 480x320 (*smartphone*)

I will start by manually change the resolution in configuration and run the full test suite,

**Comment by therunnergit** [comment]
*1024x768px* is fine, it is the default resolution.

**Comment by therunnergit** [comment]
**768x1024px** is fine.

**Comment by therunnergit** [comment]
**480x320px** fails, see https://github.com/joomla-projects/joomla-browser/issues/80

**Comment by puneet0191** [comment]
@therunnergit I have updated my PR which would address this issue on clickToolbar Function
https://github.com/joomla-projects/joomla-browser/pull/82

**Comment by chrisdavenport** [comment]
Closing as the referenced PR has been merged.  Thanks everyone.
