### ISSUE TITLE
SQL changes?

### ISSUE THREAD

**Issue by infograf768** [joomla-extensions/weblinks#150]
We are changing the collation in 3.5.0
See:
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/sql/updates/mysql/3.5.0-2015-07-01.sql

Can this be done also for weblinks when updating?

**Comment by chrisdavenport** [comment]
@infograf768 I assume this is for the utf8mb4 changes?  A PR would be welcome.

**Comment by infograf768** [comment]
Over my head, sorry. Many changes in core to move to utf8mb4, not only in the update sql files but also in "others" https://github.com/joomla/joomla-cms/tree/staging/administrator/components/com_admin/sql/others/mysql

**Comment by chrisdavenport** [comment]
Closing here as we have a PR.  Thanks @infograf768
