### ISSUE TITLE
Tests stops at installing weblinks from url

### ISSUE THREAD

**Issue by peterpeter** [joomla-extensions/weblinks#165]
The command line states
'I install extension from url "http://localhost/tests/joomla-cms3/pkg-weblinks-current.zip" '
but the correct path is
http://localhost/joomla/vcs/weblinks/tests/joomla-cms3/pkg-weblinks-current.zip
and in acceptance.suit.yml I have
url: 'http://localhost/joomla/vcs/weblinks/tests/joomla-cms3'
and thus the browser allways stops with a
'Error - Invalid URL - Unable to find install package'

**Comment by yvesh** [comment]
Hi, there are two URLs in the acceptance.dist.yml.. One in joomla-browser and one in AcceptanceHelper (scroll down). Normally they have to be the same.

**Comment by peterpeter** [comment]
Oooops....my fault:
acceptance.suite.dist.yml has changed while I'm using still an older
acceptance.suite.yml of mine, wich is never overwriten on by a pull.
Need to put that on my radar :)
