### ISSUE TITLE
Double image tab appearing

### ISSUE THREAD

**Issue by HRADigital** [joomla-extensions/weblinks#170]
Using v. 3.4.1, seams to be doubling the Image tab in the edition view.
![imagetabissue](https://cloud.githubusercontent.com/assets/8511557/11145953/0256ea80-8a02-11e5-833b-9fd0b47252c4.jpg)
This causes issues saving image's data in the database.

Only one definition of the Fieldset in models » forms » weblinks.
Fieldset is called directly in views » weblink » tmpl » edit.php
Field set is also included in line 72 of the edit view "JLayoutHelper::render('joomla.edit.params', $this)".

Might not being ignored by layouts » joomla » edit » params.php. "$displayData->get('ignore_fields')"
(Don't know where this comes from).

One solution, might be not calling the Fieldset directly in the edit.php file.
Has anyone else experience this?

**Comment by Tharalon** [comment]
Same Problem as above. I can´t save any images

**Comment by sovainfo** [comment]
See https://github.com/joomla-extensions/weblinks/pull/91

**Comment by Tharalon** [comment]
Perfect, thank´s. Prob. solved.

**Comment by sovainfo** [comment]
Ok, suggest to close this issue!
@Tharalon Don't think you can do that, neither can I. But @HRADigital and others can.

**Comment by roland-d** [comment]
Closed as fixed in #91
