### ISSUE TITLE
Tests with @depends doesn't work with new robo run:test command. 

### ISSUE THREAD

**Issue by puneet0191** [joomla-extensions/weblinks#172]
When we try to execute robo run:test command, and select the file name and along with that the test name which we want to run, if this test has a "@depends" the test is skipped and never gets executed.

**Comment by javigomez** [comment]
Tests gets executed in order from the fist function until the last inside a Cest class. Therefore I suggest that we remove the @depends knowing that they will get anyway be executed in the order that we stablish in the Cest file. That will allow to execute tests individually when running individual functions.

**Comment by puneet0191** [comment]
Yeap, I will do that :+1:  thanks

**Comment by chrisdavenport** [comment]
Closing for the time being.  If this is still relevant please re-open or submit a PR.  Thanks @puneet0191
