### ISSUE TITLE
Smart Search: Fatal Error on Index

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla-extensions/weblinks#173]
Make a Index of Smart Search stopps. In Network-Tab of Dev-Tools got: 

Fatal error: Call to undefined method JDocumentJSON::addCustomTag() in /html/Joomla/plugins/content/allweblinks/allweblinks.php on line 75

**Comment by infograf768** [comment]
"allweblinks" is not part of Joomla core

**Comment by franz-wohlkoenig** [comment]
Sorry, my fault, haven't read "all", only "weblinks".
