### ISSUE TITLE
Record last hit date

### ISSUE THREAD

**Issue by obuisard** [joomla-extensions/weblinks#175]
When a weblink is hit, there is no notion of 'when' it has been done. 
Therefore, when updating the hit counter, also record a last hit date.
It would allow links to be sorted by hit date.

**Comment by chrisdavenport** [comment]
Thanks for the suggestion.  I don't think this is something we want to implement at the present time, but if it turns out there is sufficient interest it can always be re-opened.  Thanks @obuisard
