### ISSUE TITLE
Fatal errors from weblinks component

### ISSUE THREAD

**Issue by hakanara** [joomla-extensions/weblinks#178]
I am usingweblinks 3.4.1 and Joomla 3.4.8 (both latest).

Today I saw this error twice on my error_log:
PHP Fatal error:  Call to a member function getChildren() on a non-object in /components/com_weblinks/router.php on line 210

**Comment by javigomez** [comment]
Thanks for the report @hakanara 

Could you provide steps to reproduce it?

**Comment by hakanara** [comment]
I have no idea how it came up. This error never appeared again in the log in the last 3 days. I have randomly clicked all the weblinks menus (Which were present there for more than 3 years) and items and could not manage to reproduce the error.

**Comment by yvesh** [comment]
Hmm, did you delete a weblink category? (And emptied the trash)

**Comment by chrisdavenport** [comment]
Closing as we have no clear instructions that would allow us to reproduce it.  Feel free to re-open if this is still an issue.  Thanks @hakanara
