### ISSUE TITLE
Not to be found in JED

### ISSUE THREAD

**Issue by JurgenG** [joomla-extensions/weblinks#181]
When searching for the Joomla Weblinks extension, one would expect to find it in the JED, specifically in the "weblinks" category. Isn't to be found there though.

**Comment by mbabker** [comment]
See http://extensions.joomla.org/extensions/extension/official-extensions/weblinks

When I searched JED for "weblinks" it was the first result.

As for categorization, it's a JED limitation; extensions can only be part of one category and weblinks is in an "official extensions" category.
