### ISSUE TITLE
Image field clears

### ISSUE THREAD

**Issue by Webdongle** [joomla-extensions/weblinks#182]
Reported on http://forum.joomla.org/viewtopic.php?f=728&t=903739
How to test:
Test 1:
- Create a new weblink
- Go to the tab "Images" and select an image
- Save the new weblink

The image field is now empty again.

Test 2:
- Open an existing weblink with an image
- Go to the tab "Images" and select a new image
- Save the weblink

The image field displays the original image again

Confirmed ... I tested on existing 3.4.8 that was updated with Weblinks and Jstaging with Weblinks freshly installed

**Comment by webmonkiee** [comment]
I can confirm this and having the same issue myself on 3.4.8 core.

**Comment by webmonkiee** [comment]
Hey Webdongle,

There is a fix for this here : https://github.com/joomla-extensions/weblinks/issues/89

In case you still need.
-Jon

**Comment by mbabker** [comment]
Referenced issue has been closed (PR merged).
