### ISSUE TITLE
Warning installing package in tests

### ISSUE THREAD

**Issue by javigomez** [joomla-extensions/weblinks#192]
Running the run:tests the generated package shows the following warning after install:

![screen shot 2016-03-02 at 10 58 10](https://cloud.githubusercontent.com/assets/1375475/13456949/ce971a16-e065-11e5-87f8-25aed81c5252.png)

To reproduce you can use the generated package: 
[pkg-weblinks-current.zip](https://github.com/joomla-extensions/weblinks/files/154476/pkg-weblinks-current.zip)

**Comment by yvesh** [comment]
@javigomez This is an issue in JoRobo, the language file for the package is not copied correctly. See https://github.com/joomla-projects/jorobo/issues/8

**Comment by mbabker** [comment]
Referenced issues fixed.
