### ISSUE TITLE
v3.4.1 breaks on the use of Joomla\String\String under Joomla v3.5

### ISSUE THREAD

**Issue by obuisard** [joomla-extensions/weblinks#193]
Identified files are:

- models/weblink.php
- tables/weblink.php 

in the administration part of the component.

**Comment by infograf768** [comment]
Could you explain exactly the issue? It is unclear to me.

**Comment by obuisard** [comment]
Of course!
Joomla\String\String must be replaced with Joomla\String\StringHelper in the code, as part of the changes made in Joomla 3.5 to avoid conflicts with the String class in PHP 7.

**Comment by yvesh** [comment]
Joomla\String\String isn't used in weblinks and php7cc does not seem to find any issues in weblinks.

$ php7cc src 
Checked 44 files in 3.306 seconds

**Comment by mbabker** [comment]
The current repo uses `JString`.  I can't build a package or release or update JED because the folks doing all the automated stuff have zero guidance on using their system (which broke the Phing packager that was used before) and the credentials for the JED that I found aren't valid.

**Comment by mbabker** [comment]
@javigomez please post instructions in this repo somewhere so that someone can build a 3.5 compatible weblinks package.

**Comment by yvesh** [comment]
@mbabker Build instructions can be found in the README.md file, it's basically just calling `vendor/bin/robo build` after composer install (rename jorobo.dist.ini before) .. manifest.xml isn't used atm.

Attached a build with fixed package language file working fine on 3.5 + php7.. 

[pkg-weblinks-3.4.3.zip](https://github.com/joomla-extensions/weblinks/files/157040/pkg-weblinks-3.4.3.zip)

**Comment by obuisard** [comment]
Thank you!

**Comment by mbabker** [comment]
3.5 package tagged.
