### ISSUE TITLE
Cannot install com_weblinks from webinstaller

### ISSUE THREAD

**Issue by artur-stepien** [joomla-extensions/weblinks#194]
There is bad download url in extensions.joomla.org
instead of 
[https://github.com/joomla-extensions/weblinks/releases/download/3.4.1/pkg_weblinks_3.4.1.zip](https://github.com/joomla-extensions/weblinks/releases/download/3.4.1/pkg_weblinks_3.4.1.zip)
there is
[https://github.com/joomla-extensions/weblinks/releases](https://github.com/joomla-extensions/weblinks/releases)

**Comment by yvesh** [comment]
As this is the download overview page for com_weblinks, it's imo set correctly. Else the link would need to be updated every time a new release is made..

**Comment by artur-stepien** [comment]
Well, that is the main reason why download url is there? So people would get direct download url? For extensions.joomla.org that can be accepted to have only a directory of releases. But this is also in webinstaller plugin. When user try to install this component from webinstaller he gets error cause this is not a package, this is html page.

**Comment by mbabker** [comment]
The download button on JED listing pages points to a listing page where you can get downloads for the extension.  Support for installing via the Install from Web requires a different config file.  Lucky us the credentials for the account seem to not be working.

**Comment by chrisdavenport** [comment]
Closing as the link has now been updated.  Thanks everyone.
