### ISSUE TITLE
Apache error 500 after upgrading to 3.5.0

### ISSUE THREAD

**Issue by QkiZMR** [joomla-extensions/weblinks#204]
Whole site is working on Joomla 3.5.0 without problem, but not weblinks. Version 3.4.1 and 3.5.0 causes server error 500. Worse thing is that no sign of error in apache error log, even in debug loglevel.

**Comment by kshitijSharma2014** [comment]
@QkiZMR please go through [http://stackoverflow.com/questions/4731364/internal-error-500-apache-but-nothing-in-the-logs](url) 
In this link they have shown a way to view the errors.

**Comment by yvesh** [comment]
@QkiZMR Did you try setting error reporting to development in the joomla configuration? Also enable joomla debugging please. On which view (url) does the error show up?

**Comment by QkiZMR** [comment]
@kshitijSharma2014 thanks for that link but this not help. But after changing php to verbose mode now I got blank page. In apache access log is:

`...GET /blog/links.html HTTP/1.1" 200 239...`

After changing error reporting to development joomla admin panel stops working. In browser I see "ERR_CONTENT_DECODING_FAILED" (Chrome). But /links.html page show errors:

`Fatal error: Call to a member function setState() on a non-object in /var/www/qkiz.pl/blog/modules/mod_related_items/helper.php on line 44`

**Comment by QkiZMR** [comment]
Ok, after disabling Related Articles module everything back to normal. Which means that is not Weblinks problem.

**Comment by mbabker** [comment]
That was fixed with https://github.com/joomla/joomla-cms/pull/9519

**Comment by QkiZMR** [comment]
Is that fix is already in 3.5.0?

**Comment by mbabker** [comment]
It'll be in 3.5.1 as it was patched after 3.5.0 was released.

**Comment by QkiZMR** [comment]
I patched helper.php by myself with patch from link. Thanks, problem solved.
