### ISSUE TITLE
Create a Menu-Link directly to a WebLinks URL

### ISSUE THREAD

**Issue by Fuzariane** [joomla-extensions/weblinks#211]
![mediatheque stmande - administration - menus ajouter un lien de menu - go_2016-05-06_13-29-29](https://cloud.githubusercontent.com/assets/8916528/15071771/84059d86-138e-11e6-91ff-e2f77a452e83.jpg)

It would be create for Webmasters having a direct access to URLS of a weblink. We could add "external links" more efficiently and they would be changed when has changed in the component.

**Comment by chrisdavenport** [comment]
So you are proposing a new front-end view that would point to a single weblink.  When you click on it, it will redirect to the URL associated with the weblink.  Is that right?

**Comment by franz-wohlkoenig** [comment]
can this Issue be closed as #325 is merged?

**Comment by franz-wohlkoenig** [comment]
@Fuzariane can you please close this issue?

**Comment by joomdonation** [comment]
Closing this issue because we now have a menu item type to display weblink item already.
