### ISSUE TITLE
Weblink created date not showed on Search view

### ISSUE THREAD

**Issue by tramber91** [joomla-extensions/weblinks#212]
Hi
On Joomla search view I cannot see the weblink created date

I succeed to see them with modification of file
/plugins/search/weblinks/**weblinks.php**

line  177

`$query->select('a.title AS title, \'\' AS created, a.url, a.description AS text, ' . $case_when . "," . $case_when1)`

replaced by

`$query->select('a.title AS title, a.created AS created, a.url, a.description AS text, ' . $case_when . "," . $case_when1)`

 It is logical ?

thanks

Bertrand

**Comment by ZerooCool** [comment]
He is really ! He is so ! He is great ! He is perfect ! He is nice ! He helped ! He found ! He saved me! He is really ! He is so ! He is great ! He is perfect ! He is nice ! He helped ! He found ! He saved me! He is really ! He is so ! He is great ! He is perfect ! He is nice ! He helped ! He found ! He saved me!

Thanks ! Resolved !

**Comment by yvesh** [comment]
Hi Bertrand,
can you make a pull request to weblinks with it? Thank you :-)
Yves

**Comment by tramber91** [comment]
hi yves

seems i have no right to do that

**Comment by yvesh** [comment]
Everybody can do pull requests, you just can't push directly into the extension ;)

https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests
http://extensions.joomla.org/blog/item/how-to-contribute-to-joomla-through-github

**Comment by ZerooCool** [comment]
Hi, sorry friends, i look my site, i seach a word, and, i have the SAME problem with the category.

1. Éditoriaux Technologies
    (Catégorie) 
     - Informatique, sciences, dossiers non classés.  ... 
    Créé le 
2. Éditoriaux Sciences
    (Catégorie) 
     - Information et Communication. 
    Créé le 

Can you help me ?

**Comment by yvesh** [comment]
@ZerooCool This is the wrong repository for that. Please write an issue (more extensive than what you wrote here, best including screenshots) at Joomla! core.
