### ISSUE TITLE
Error when trying to update to 3.5.0

### ISSUE THREAD

**Issue by marksou** [joomla-extensions/weblinks#213]
HI, I'm getting the following error when attempting to update to 3.5.0 from 3.4.0.
`Duplicate column name 'version' SQL=ALTER TABLE `#__weblinks` ADD COLUMN `version` int(10) unsigned NOT NULL DEFAULT '1'
Package Update: There was an error installing an extension: com_weblinks.zip`

**Comment by yvesh** [comment]
@wilsonge can you have a look please? The script.php update code is from you, not sure why it is executed on the first glance.

https://github.com/joomla-extensions/weblinks/blob/master/src/administrator/components/com_weblinks/script.php#L228

**Comment by chrisdavenport** [comment]
Code looks correct to me.  Closing for now.  It can be re-opened if there is still an issue that needs addressing.  Thanks for reporting @marksou
