### ISSUE TITLE
Fields are cleared on the frontend in case of error

### ISSUE THREAD

**Issue by dforsi** [joomla-extensions/weblinks#23]
I did a clean installl of Joomla 3.3.6 accepting all defaults and I only added a menu item to "Submit a Web Link", no other changes.
When adding a duplicated weblink from the frontend I get the expected error message but all form fields are empty, while doing the same from the backend all field contents are preserved and I still get error message, as expected.

**Comment by chrisdavenport** [comment]
Due to the age of this issue I'm going to close it at this time.  If you think this is still an issue please re-open it.  Thanks.
