### ISSUE TITLE
Bridge search with Joomla in your wikimedia

### ISSUE THREAD

**Issue by ZerooCool** [joomla-extensions/weblinks#236]
#### Steps to reproduce the issue
Not exist

#### Expected result
Search and found keyword in the wiki media

#### Actual result
Not exist

#### System information (as much as possible)
Linux / All

#### Additional comments
Can you make that, day after day, with me ? I want learn and use that option.

I want learn the best way.
Thank you.

**Comment by chrisdavenport** [comment]
I'm sorry, I don't understand what you're asking for.  Can you explain it in more detail?

**Comment by ZerooCool** [comment]
Outch, wrong URL, it's not a work with weblink.
I have post to joomla cms.
I have a wikimedia. I use Joomla! too.

I want learn and create a bridge, then, when i search a WORD, with the Joomla search tool, i can see answer from wikimedia.

I say, i m a noob, i need found ressources, idea, a good way. It's not easy, but, it's a good project.

I search but not found this search bridge to include wikimedia content ( title , or, title + content )


I use 2 bdd mysl, 1 for joomla! and 1 for the wiki.

If you have the good idea, give me ? i give you a beer, it's free, take it.
Thank you for your answer.

**Comment by yvesh** [comment]
This is the wrong place for such questions. You should ask it at [Joomla! Forum](http://forum.joomla.org/) or hire somebody for it.

// Closed

**Comment by ZerooCool** [comment]
Yes. Thank you.
