### ISSUE TITLE
Fix False Positive on Travis Job for PHP 5.5

### ISSUE THREAD

**Issue by puneet0191** [joomla-extensions/weblinks#259]
We need to fix False positive on 
AdministratorCategoriesCest: Test Unpublish a Category in /administrator/
administratorUnpublishCategory, 

I see "1 category successfully unpublished",{"id":"system-message-container"}

**Comment by puneet0191** [comment]
See PR https://github.com/joomla-extensions/weblinks/pull/258

**Comment by yvesh** [comment]
It's an general issue with the system-message-container, maybe we should skip it completely and fall back to another solution. It's not only falling in weblinks, but we run into the same issue with the  GSoC 2016 automated testing project.

// cc @pritalpatel

**Comment by 810** [comment]
yes, we need to fix this asap, because now 1 php is always failing on each check.

**Comment by Hackwar** [comment]
Travis is dead, so I'm closing this one.
