### ISSUE TITLE
make Drone.io execution more performant adding cache to composer packages

### ISSUE THREAD

**Issue by javigomez** [joomla-extensions/weblinks#264]
I have noticed that the first minutes of the build are dedicated to download all the composer require-dev files (https://github.com/joomla-extensions/weblinks/blob/master/composer.json#L13). Despite composer.lock file is tracked and we are doing 'composer install' (and not 'composer update) is still taking several minutes to download all. I'm creating this issue so we can check in the future for ways to improve performance in that area.

**Comment by Hackwar** [comment]
Has been fixed since.
