### ISSUE TITLE
Component delivers 303 status code instead of 301

### ISSUE THREAD

**Issue by DJBenz** [joomla-extensions/weblinks#271]
Referring to this thread on the Joomla forum: http://forum.joomla.org/viewtopic.php?f=714&t=936283

This was recently brought up by Sucuri after checking an issue I received via Google Webmaster Tools

> Your website redirects the visitor using the following method:
>
>-------------------------[begin test snippet]-------------------------
>$ curl -sD - -L "http://www.horrortalk.com/component/weblinks/weblink/50-movie-distributors-us/46->uncork-d-entertainment.html?Itemid=101&task=weblink.go" |head -n 3
>
>HTTP/1.1 303 See other
>Date: Tue, 04 Oct 2016 22:04:10 GMT
>-------------------------[begin test snippet]-------------------------
>
>See the "303 See other"? This is the status code provided by your website. However, Google needs a >301 status code in order to understand that anything after that, is not on your website anymore.

It was suggested by user mbabker to raise it here.

**Comment by yvesh** [comment]
Hi @DJBenz, hmm thank you for reporting. 

It's basically that weblinks uses the Joomla redirect method here. Which has a 303 as default..

https://github.com/joomla-extensions/weblinks/blob/master/src/components/com_weblinks/controllers/weblink.php#L308

The second parameter, would take the status code (e.g. 301) in this case. Going to make a PR on that when i find some time in the next days..

**Comment by zero-24** [comment]
PR is: #272 so this here can be closed :smile:
