### ISSUE TITLE
Les liens affichent title="<p>..............text..........</p>

### ISSUE THREAD

**Issue by ZerooCool** [joomla-extensions/weblinks#275]
Bonjour, je cherche :
1 - A trouver l'adresse github du projet, allweblinks, si elle existe.
2 - à résoudre ce bogue suivant :

Ce module n'est surement plus maintenu, et, j'aimerais savoir si vous pensez qu'il m'est possible de le partager en l'état sur github ? Je voudrais bien qu'il soit maintenu...

Merci de regarder mon problème, le module et le plugin allweblinks sont ajoutés en pièce jointe sur le forum.

Mon problème est l'attribut title="" du lien qui affiche une valeur entourée par <p> .... </p>
Vous pouvez observer sur www.visionduweb.eu , à droite , l'annuaire de lien en arborescence.
**Les liens affichent title="<p>..............text..........</p>"**

http://www.aide-joomla.com/forum/aides-generales-joomla/30310-mod-weblinks-afficher-l-annuaire-en-arborescence-probleme-de-title-au-survol

**Comment by zero-24** [comment]
@infograf768 can you help here with the translation?

Or can you @ZerooCool post in English?

**Comment by ZerooCool** [comment]
Joomla User Group - France - Alsace
Serge Billon je t'ai répondu sur aide-joomla *

dans le fichier : "modules/mod_allweblinks/tmpl/default.php"
Ligne 109
ajouter :
$title=strip_tags ($title);

**Comment by infograf768** [comment]
@ZerooCool 
Merci de ne plus poster sur le git joomla concernant un problème avec une extension tierce.

**Comment by ZerooCool** [comment]
infograf768, désolé, je fais au mieux, mais, weblinks est une extension tierce non ?
J'avais cru comprendre qu'elle n'était plus maintenue par Joomla! alors je pensais bien faire en ajoutant des informations complémentaires sur cette page weblinks concernant allweblinks, qui affiche les weblinks d'une autre façon, que je trouve vraiment pratique.

**Comment by infograf768** [comment]
Weblinks is maintained by core, not any 3rd party extension.
for issues concerning com_weblinks, (NOT any 3pd extension) please post in
https://github.com/joomla-extensions/weblinks
and in English please 😄
