### ISSUE TITLE
Use the new useglobal in weblinks

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-extensions/weblinks#277]
#### Steps to reproduce the issue

A séries of PR added use global value to use global option. Ex: https://github.com/joomla/joomla-cms/pull/12865
IMHO this should be done for weblinks too

#### Expected result

Same as core

#### Actual result

Not as core

#### System information (as much as possible)

Latest

#### Additional comments

None

Pinging @Bakual if he wants to do this too for weblinks

**Comment by Bakual** [comment]
As you wish.

Closing since we have a PR.

**Comment by andrepereiradasilva** [comment]
thanks @Bakual !
