### ISSUE TITLE
Unnecessary closing div tag

### ISSUE THREAD

**Issue by QkiZMR** [joomla-extensions/weblinks#28]
Steps to reproduce the issue

Display weblinks component. Unnecessary tag in /components/com_weblinks/views/categories/tmpl/default.php causes mess in template. Line number 17.

Expected result

Correct display of weblinks component. Solution is create weblinks override without closing div tag.

Actual result

Mess in weblinks in custom template.

System information (as much as possible)

Linux, Apache, Mysql

Screenshots from messed webpage and corrected one:
http://image.qkiz.pl/di/UBY5/bad.png
http://image.qkiz.pl/di/TNQP/good.png

**Comment by zero-24** [comment]
@QkiZMR please try: https://github.com/joomla-extensions/weblinks/pull/33 Thanks!

**Comment by QkiZMR** [comment]
Ok, thx.

**Comment by zero-24** [comment]
@QkiZMR are you able to test it? If yes please comment on #33 so we can move it forward and fix it with 3.4.1 of com_weblinks :smile:

**Comment by QkiZMR** [comment]
Diff files from https://github.com/joomla/joomla-cms/pull/6134/files doesn't match to files from my Joomla ver. 3.4.1 Stable
