### ISSUE TITLE
Weblinks translation (crodwin?)

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-extensions/weblinks#280]
Crowdin has several joomla extensions for translation: https://crowdin.com/project/joomla-patchtester

It currently supports translations of 3 extensões already:
- https://github.com/joomla-extensions/patchtester 
- https://github.com/joomla-extensions/facebook-auth
- https://github.com/joomla-projects/plg_content_joomlarrssb

Shouldn't weblinks be supported too?

**Comment by yvesh** [comment]
@andrepereiradasilva sounds like a good idea. 👍

**Comment by infograf768** [comment]
We replied to this on the main github repo
