### ISSUE TITLE
What is the plan to fix the CS Travis problem?

### ISSUE THREAD

**Issue by zero-24** [joomla-extensions/weblinks#282]
#### Steps to reproduce the issue

https://travis-ci.org/joomla-extensions/weblinks/jobs/180140898

#### Expected result

No CS issue

#### Actual result

CS issues on package / subpackage tag

#### System information (as much as possible)

https://github.com/joomla-extensions/weblinks/commit/3cf373b43cc38e0d2a15bbfb35faab6366ffb845

Why did we removed the subpackage tag?
How should this issue to be fixed?

**Comment by chrisdavenport** [comment]
It was a consequence of running robo as part of the release procedure.  The fix is simply to correct the header text in jorobo.dist.ini and run vendor/bin/robo headers again.

**Comment by zero-24** [comment]
Ok. Thanks so i'm closing here. Thanks
