### ISSUE TITLE
drone.yml needs updating for Drone 0.5

### ISSUE THREAD

**Issue by yvesh** [joomla-extensions/weblinks#305]
The current drone.yml is not working with drone 0.5 (no tests done, just tests successful)

**Comment by zero-24** [comment]
Should this not just be a c&p + some changes from https://github.com/joomla/joomla-cms/blob/staging/.drone.yml ?

**Comment by yvesh** [comment]
@zero-24 yep :)

**Comment by wilsonge** [comment]
Fixed to drone v1 with https://github.com/joomla-extensions/weblinks/commit/8712d4033a1453f858a78004ab1ed5d185c60409
