### ISSUE TITLE
Fetch the current version of webdrivers

### ISSUE THREAD

**Issue by astridx** [joomla-extensions/weblinks#308]
If I clone weblinks and execute 

`composer install `

in my directory 
/var/www/html/weblinks/vendor/joomla-projects/selenium-server-standalone/bin/webdrivers/chrome/

are old Webdrivers (July 2016) which are not executable. 

Am I doing something wrong or do I have to fetch the current version of selenium-server-standalone manually?

**Comment by yvesh** [comment]
No you, have to chmod+x the webdriver. It's also fixed with #304, but waiting for @jatitoam to fix jorobo here.

**Comment by astridx** [comment]
But why is the date Jluy 2016. Didn't we update this in December: https://github.com/joomla-projects/selenium-server-standalone/pull/34

**Comment by yvesh** [comment]
Did not check, maybe because of the composer.lock. Should be 3.0.1.2

https://github.com/joomla-extensions/weblinks/blob/master/composer.json#L18

**Comment by astridx** [comment]
I have the current composer file: https://github.com/joomla-extensions/weblinks/blob/master/composer.json#L18
I cloned it a few hours ago. So that is not the problem.
But after
`composer install`
my webdrivers are

```
-rw-rw-r-- 1 astrid astrid  5285376 Jul  4  2016 chromedriver.exe
-rw-rw-r-- 1 astrid astrid  6464400 Jul  4  2016 chromedriver_linux_32
-rw-rw-r-- 1 astrid astrid  5806960 Jul  4  2016 chromedriver_linux_64
-rw-rw-r-- 1 astrid astrid 11581748 Jul  4  2016 chromedriver_mac
-rw-rw-r-- 1 astrid astrid     1091 Jul  4  2016 README.md
```

It is no problem for me. I can clone the project  joomla-projects/selenium-server-standalone and take the webdrivers from there. I did this today. In the project joomla-projects/selenium-server-standalone the webdrivers are like this:
```

-rw-rw-r-- 1 astrid astrid  7477760 Feb 13 20:53 chromedriver.exe
-rwxrwxr-x 1 astrid astrid  7609124 Feb 13 20:53 chromedriver_linux_32
-rwxrwxr-x 1 astrid astrid  7466136 Feb 13 20:53 chromedriver_linux_64
-rwxrwxr-x 1 astrid astrid 10256192 Feb 13 20:53 chromedriver_mac
-rw-rw-r-- 1 astrid astrid     2085 Feb 13 20:53 README.md
```

But I wonder if I the only one with this probleme and in this case I like to understand what I do wrong.

**Comment by astridx** [comment]
I was wront yesterday. I only had a look into the file composer.json. 

Gut in composer.lock the joomla-projects/selenium-server-standalone is locked:
https://github.com/joomla-extensions/weblinks/blob/master/composer.lock#L1478

Is it a problem to modify composer.lock so that joomla-projects/selenium-server-standalone version 3 can be loaded?

**Comment by yvesh** [comment]
@astridx Go for it and let's see what travis says ;) 

But only update Selenium, not Robo.li and JoRobo (these have issues)

**Comment by astridx** [comment]
I tried to update the composer.json for selenium 3.0.1.2. 
For this edited the composer.json and I deleted the composer.lock. 
When I run the command "composer install" I get the following message:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package composition/robo could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

```

If I understand everything right it is not possible to load the package composition/robo.

I only changed the value for selenium-standalone-sever. So I wonder why I get an error message for composition/robo? 

Despite of this I opened https://packagist.org/ and searched for the package composition/robo. But I could not find a package with this name. 

Do we have an error in our composer.json?

**Comment by yvesh** [comment]
@astridx yes and not only here. it should be:

    `"consolidation/robo": "^1.0.0"`

not composition

**Comment by 810** [comment]
@astridx did you fixed the issue? then please close the issue

**Comment by astridx** [comment]
@810 Thanks
