### ISSUE TITLE
Options > Allow Captcha > unclear Default

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla-extensions/weblinks#309]
### Steps to reproduce the issue
Open `Options > Allow Captcha`, User get:
![1](https://cloud.githubusercontent.com/assets/8235763/22967035/0ce746e8-f365-11e6-97de-6ce9c0c6fe61.JPG)

### Expected result
Set Default (i.e. "Yes / No)
### System information (as much as possible))
weblinks-3.6.0-rc-pre5
macOS Sierra, 10.12.3
Firefox 51.0.1
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by zero-24** [comment]
@franz-wohlkoenig this should list all captcha plugins you have installed and configured.

Use default means -> Global Config value
None Selected -> No Captcha plugins should be used.

**Comment by zero-24** [comment]
So if you have a captcha configured you can't just say Yes and No ;)

**Comment by franz-wohlkoenig** [comment]
True *g Thanks for Information
