### ISSUE TITLE
SQL error when versioning enabled

### ISSUE THREAD

**Issue by bertmert** [joomla-extensions/weblinks#31]
Update J!2.5.28 to 3.4.1 (with known problems).

After applying patch from
https://github.com/joomla-extensions/weblinks/pull/30
(Thanks for it!)

and actvating Versioning in Weblinks > Options we have an SQL error while saving a weblink.

"
Error

Save failed with the following error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND `sha1_hash` = '093f558adc1ca35ced94ba8xyz'' LIMIT 0, 1' at line 3 SQL=SELECT * FROM `xxxx_ucm_history` WHERE `ucm_item_id` = 9 AND `ucm_type_id` = AND `sha1_hash` = '093f558adc1ca35ced94ba8xyz' LIMIT 0, 1
"

Error is here (no ucm_type_id)
```
AND `ucm_type_id` = AND `sha1_hash`
```
/libraries/cms/table/contenthistory.php

**Comment by zero-24** [comment]
@bertmert please try the new download package at: https://github.com/joomla-extensions/weblinks/pull/30#issuecomment-90764517

**Comment by Bakual** [comment]
Will be fixed with https://github.com/joomla-extensions/weblinks/pull/30
