### ISSUE TITLE
Options: 2 Times `Image Float`

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla-extensions/weblinks#311]
### Steps to reproduce the issue
Open `Options`: Tab `Web Link`:
![1](https://cloud.githubusercontent.com/assets/8235763/22971764/17852b30-f377-11e6-96b5-e0781f7d0452.JPG)
### System information (as much as possible)
weblinks-3.6.0-rc-pre5
macOS Sierra, 10.12.3
Firefox 51.0.1
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by zero-24** [comment]
That are two different options. They also need different description. I can fix this later.

**Comment by franz-wohlkoenig** [comment]
had tested on Joomla 3.7, should test on 3.6.5, so closing this
