### ISSUE TITLE
Options: First Image > Image Float won't work

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla-extensions/weblinks#312]
### Steps to reproduce the issue
`Options` > Tab `Images` > `First Image`, Image float left, indipendent what User set.
### System information (as much as possible)
weblinks-3.6.0-rc-pre5
macOS Sierra, 10.12.3
Firefox 51.0.1
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by zero-24** [comment]
did you try both options? as the first option should be float first and the seccond otion foloar seccond. ;)

**Comment by franz-wohlkoenig** [comment]
i tried with first alone and second too: Only second goes left or none, first stay left.

**Comment by zero-24** [comment]
Thanks i check this later for together with the other issue.

**Comment by franz-wohlkoenig** [comment]
thanks @zero-24

**Comment by franz-wohlkoenig** [comment]
had tested on Joomla 3.7, should test on 3.6.5, so closing this
