### ISSUE TITLE
Installation issue with MariaDB

### ISSUE THREAD

**Issue by Sulpher** [joomla-extensions/weblinks#32]
I've had Joomla 3.3.6 with com_weblinks. Soon Joomla was updated to 3.4.1 and com_weblinks is needed to be updated. I took latest version of weblinks component from here, tried to install and got this error message:

Warning
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'delimiter ';;' create procedure weblinks_schema_change() begin /* delete colum' at line 1 SQL=delimiter ';;' create procedure weblinks_schema_change() begin /* delete columns if they exist */ if exists(SELECT * FROM information_schema.columns WHERE table_name = '#__weblinks' AND column_name = 'sid') THEN ALTER TABLE `thm7_weblinks` DROP COLUMN `sid`;

Joomla 3.4.1
DB: 5.5.37-MariaDB-wsrep

**Comment by mbabker** [comment]
Please follow https://github.com/joomla-extensions/weblinks/issues/25 and linked pull requests
