### ISSUE TITLE
Question about the version number in the file jorobo.php.

### ISSUE THREAD

**Issue by astridx** [joomla-extensions/weblinks#341]
It is confusing for me, that the version in the file /weblinks/dist/pkg-weblinks-current.zip is 3.6.0-beta. 
I saw, that this version is taken out of the file jorobo.php.
Can I change this version number or is there a reason for this number?

**Comment by zero-24** [comment]
IIRC this can be changed to 3.7.0 can you confirm @yvesh ?

**Comment by astridx** [comment]
As I was on the branch I created the PR https://github.com/joomla-extensions/weblinks/pull/342

**Comment by yvesh** [comment]
3.7.0-beta-1 would be better, but it's okay ;)

**Comment by zero-24** [comment]
Closing as the PR is beeing merged
