### ISSUE TITLE
categories list view broken

### ISSUE THREAD

**Issue by JohnnyDevNull** [joomla-extensions/weblinks#35]
com_weblinks\site\views\categories\tmpl\default.php

the closing div in the last line have to be removed!

See also: http://www.joomlaportal.de/joomla-3-x-installation/313482-sammelthread-upgrade-von-2-5-auf-3-3-welche-vorgehensweise-ist-hilfreich-29.html#post1589395

**Comment by bertmert** [comment]
Please see
https://github.com/joomla/joomla-cms/pull/6134
Do not remove but add opening DIV.

**Comment by bertmert** [comment]
See PR https://github.com/joomla-extensions/weblinks/pull/36

**Comment by zero-24** [comment]
@JohnnyDevNull this can be closed as we merge a fix here: https://github.com/joomla-extensions/weblinks/pull/33 Thanks :smile:
