### ISSUE TITLE
Remove redundant word #14607

### ISSUE THREAD

**Issue by astridx** [joomla-extensions/weblinks#351]
Because of https://github.com/joomla/joomla-cms/pull/14607/files we have to make much changes in our tests.
Only one example (where we have to delete the word successfully): https://github.com/joomla-extensions/weblinks/blob/master/tests/acceptance/administrator/AdministratorCategoriesCest.php#L65

**Comment by alikon** [comment]
if we need to change a test for a string changes we have made that test in the wrong way
```php
$I->expectTo('see a success message after saving the category');
$I->see('Category successfully saved', ['id' => 'system-message-container']);
```
we need to see on database if a is "Category successfully saved" instead

i remember some works on this matter at the Munich Sprint

**Comment by astridx** [comment]
We have PR: https://github.com/joomla-projects/joomla-browser/pull/135/files
