### ISSUE TITLE
weblinks broken after switch from php 5.6 to 7.X

### ISSUE THREAD

**Issue by Maderthaner** [joomla-extensions/weblinks#352]
### Steps to reproduce the issue

I just switched Joomla's server PHP version from PHP 5.6.x to 7.1.5 or 7.0.X
### Expected result

Website including links works as before after clearing cache.
### Actual result

When clicking on weblinks, it is stuck at the step, e.g., HTTX//URL/xxx?task=weblink.go&id=35 and doesn't actually go to the link destination (just blank page).
Also in den Admin Backend, I cannot edit links anymore (just goes to blank page as well).
### System information (as much as possible)

Joomla Sys Info:

PHP Built On Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
Database Version 5.5.55-0+deb7u1-log
Database Collation latin1_german2_ci
Database Connection Collation utf8mb4_general_ci
PHP Version 7.1.5
Web Server Apache
WebServer to PHP Interface cgi-fcgi
Joomla! Version Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Joomla! Platform Version Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:53.0) Gecko/20100101 Firefox/53.0

Joomla PHP Info:
Relevant PHP Settings
Setting Value

Safe Mode Off
Open basedir None
Display Errors On
Short Open Tags On
File Uploads On
Magic Quotes Off
Register Globals Off
Output Buffering Off
Session Save Path /tmp
Session Auto Start 0
XML Enabled Yes
Zlib Enabled Yes
Native ZIP Enabled Yes
Disabled Functions None
Multibyte String (mbstring) Enabled Yes
Iconv Available Yes
Mcrypt Enabled Yes
Maximum Input Variables 5000
### Additional comments

I'm using 1und1.de hosting. Website is working fine under PHP 5.6

**Comment by zero-24** [comment]
Please enable debug and set the error reporting to maximum.

I can not reproduce such error like this on `7.1.1-nmm1`

**Comment by Maderthaner** [comment]
If I follow a link a la "URL?task=weblink.go&id=35" then I receive
> Fatal error: Cannot use Joomla\String\String as String because 'String' is a special class name in /xxx/htdocs/administrator/components/com_weblinks/tables/weblink.php on line 12

And, if I follow it in the admin interface I receive:
> Fatal error: Cannot use Joomla\String\String as String because 'String' is a special class name in /xxx/htdocs/administrator/components/com_weblinks/models/weblink.php on line 13

**Comment by zero-24** [comment]
Which version of weblinks do you use?

https://github.com/joomla-extensions/weblinks/blob/3.6.0/src/administrator/components/com_weblinks/tables/weblink.php#L12-L13

The last stable version 3.6.0 does not include that line.

**Comment by Maderthaner** [comment]
It says 3.4.1

Isn't that component updated with the joomla core files upgrade?

How do I update it anyway? It doesn't show out of date...

**Comment by astridx** [comment]
Can you see an update message if you search updates in the Joomla backend menu 
Extensions | Updates 
and then the toolbar button "Find updates"?

You can find all releases here: https://github.com/joomla-extensions/weblinks/releases

The current stable release is 3.6.0: https://github.com/joomla-extensions/weblinks/releases/tag/3.6.0

**Comment by Maderthaner** [comment]
I'm usually religiously updating my extensions. But it doesn't show any updates for the Weblinks component/extension when pressing find updates. I wonder why? Are my update repositories wrong? Did I do something wrong going from 3.4 up...? I wonder what other extension are updated now but don't show...

Thanks for your help. this is amazing. I was able to solve the problem by upgrading to the version 3.6.0

**Comment by zero-24** [comment]
>  wonder why? Are my update repositories wrong? Did I do something wrong going from 3.4 up...?

Please check your update sites ;)

**Comment by Maderthaner** [comment]
Well… 

There are a bunch of them. Any hint which one I should add to get update notifications such as the one for Weblink?

That would be much appreciated since my quick googling didn’t really help.

**Comment by zero-24** [comment]
the URL should be `https://raw.githubusercontent.com/joomla-extensions/weblinks/master/manifest.xml`

**Comment by Maderthaner** [comment]
Thanks! 

I found the problem. I had an old extension in there (RokUpdate) that was preventing the rebuild of the update URLs. I deleted the old extension and was able to rebuild the update links. Now the Weblink update URL shows.

Thanks again a lot! I also found another out-of-date extension after I rebuild the links!!!

Best
