### ISSUE TITLE
Feature Request: Import Links and Bookmarklet

### ISSUE THREAD

**Issue by thatgrrl** [joomla-extensions/weblinks#355]
If possible, could features be added to Web Links which would let me import my old bookmarks and my links from my old site. The site was WordPress but I have changed to Joomla this summer. So far, I can't find a way to import all my links. The XML/ OPML file from WordPress does not work with any other software I tried, including web based things I found. I did finally make a CSV file but it is still not working for J2XML. But, either way, Web Links does not have an import links feature. 

Also, a bookmarklet which would let me add links as I find them while online, with the Chrome or Firefox web browser. If this could post to Web Links, letting me select a category and then choose to write a description, that would help a lot. WordPress does have a bookmarklet with the Link Manager plugin. Although WordPress also stopped supporting the Link Manager with the core, I still use links on my sites and I had been using https://wordpress.org/plugins/restore-lost-functionality/ 

A link checker would be a great bonus. Something to alert me if I already have a link listed on my site. Also, checking for broken links and saving me from going through them all manually to avoid link rot. 

I would really like to use Web Links to build a resource link directory on my site. I don't really understand why link management/ directories have fallen out of favour when content curation is popular. I curate and write my own content, part of that is a list of other online resources, groups, etc. Ideally, I'd like links displayed something like alltop/ popurl which is a topic based collection of links. 

I can think of other features but being able to import links and have a bookmarklet are the main two I would especially like. Please :)

**Comment by joomdonation** [comment]
Sorry but we don't have plan to support this feature. So closing.
