### ISSUE TITLE
View "Display Select" is different of View other Components

### ISSUE THREAD

**Issue by ghost** [joomla-extensions/weblinks#356]
### Steps to reproduce the issue
Create Menu `List Web Links in a Category`, 
set in Tab "List Layouts" Label `Display Select` to `Show`, View looks like:
![bildschirmfoto 2017-07-25 um 06 25 43](https://user-images.githubusercontent.com/8235763/28555985-81c33eba-7103-11e7-9359-5d9b1f442d5e.jpg)
in other Views it looks like:
![bildschirmfoto 2017-07-25 um 06 26 09](https://user-images.githubusercontent.com/8235763/28556012-9d322652-7103-11e7-9493-8d271a338be9.jpg)
### System information (as much as possible)
Web Links 3.6.0
macOS Sierra, 10.12.5
Firefox 54.0 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by astridx** [comment]
@franz-wohlkoenig Are you sure?
I just created a menu item for a category list in com_content and it looks similar.
![category list content with display select](https://user-images.githubusercontent.com/9974686/32407272-ce4a1582-c186-11e7-8df5-27152256a162.png)
![category weblink with display select](https://user-images.githubusercontent.com/9974686/32407273-ce6ace62-c186-11e7-9118-a4aa263de949.png)

**Comment by franz-wohlkoenig** [comment]
I compared Links sorted by Tag with sorted by Link-Category.

**Comment by astridx** [comment]
@franz-wohlkoenig Thank you for explaining. Now I understand.

You mean the view
**com_tags** / view=tag (Here you choose the content type web links)
and
**com_weblinks** / view=category

As com_content / view=category looks like the web links view I am not sure which few is the wrong one? 
What do the others mean?

**Comment by franz-wohlkoenig** [comment]
Should this stay open?

**Comment by joomdonation** [comment]
Let's closing this for now.
