### ISSUE TITLE
administrator page is not open

### ISSUE THREAD

**Issue by principalkuce** [joomla-extensions/weblinks#357]
### Steps to reproduce the issue
my website is www.kuce.ac.in.  it built with joomla 2.5 version, yesterday i updated JH spalsh screen extension through cpannel.after that  i opened link i.e. : 
kuce.ac.in/administrator it gives error message:
Fatal error: Call to undefined method JAdministrator::getBody() in /home/content/88/13955388/html/plugins/system/jhsplashscreen/jhsplashscreen.php on line 37

please reolve the issue

**Comment by zero-24** [comment]
@principalkuce As you see in the error message it points to the plugin you have installed.

Inorder to do a quickfix you can rename the folder `/home/content/88/13955388/html/plugins/system/jhsplashscreen` =>  `/home/content/88/13955388/html/plugins/system/__jhsplashscreen`

Please contact the developer of that plugin than with your error message.

**Comment by principalkuce** [comment]
[500 - Error_ 500.pdf](https://github.com/joomla-extensions/weblinks/files/1224511/500.-.Error_.500.pdf)
[kuce.ac.pdf](https://github.com/joomla-extensions/weblinks/files/1224510/kuce.ac.pdf)
