### ISSUE TITLE
Double Field in "Options"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla-extensions/weblinks#360]
### Steps to reproduce the issue
Open Weblinks-Options, in first Tab "Web Link" got 2-Times a Field "Image Float":
![bildschirmfoto 2017-08-29 um 20 11 37](https://user-images.githubusercontent.com/8235763/29836843-b62c94c6-8cf6-11e7-847a-38be35511fe1.jpg)
I guess its about Icon and Link-Image, which should be shown in fieldname.
### Test on
Joomla 3.8.0-beta4
weblinks 3.6.0
macOS Sierra, 10.12.5
Firefox 54.0 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by astridx** [comment]
I think we do not need ether of this [image float fields](https://github.com/joomla-extensions/weblinks/blob/84a98f9718a4dbecc3f1447839baa040c460b3e8/src/administrator/components/com_weblinks/config.xml#L87) for the icon. The icon used no float: [see here.](https://github.com/joomla-extensions/weblinks/blob/84a98f9718a4dbecc3f1447839baa040c460b3e8/src/components/com_weblinks/views/category/tmpl/default_items.php#L77)

Are I am right?

**Comment by franz-wohlkoenig** [comment]
These 2 Fields are independent of Icon-Field. Please see also #365

**Comment by astridx** [comment]
@franz-wohlkoenig 
I believe the two fields mention in this issue have no use. 
If you want to float the image of a weblink like you do it in https://github.com/joomla-extensions/weblinks/issues/365 you can set this option when you insert the [image](https://github.com/joomla-extensions/weblinks/blob/2ebe811b6046052f32d2f90e6239032da151dcf8/src/administrator/components/com_weblinks/models/forms/weblink.xml#L318).

So I would suggest to delete this two fields.

**Comment by franz-wohlkoenig** [comment]
Images in Weblink:
![bildschirmfoto 2017-08-31 um 21 38 53](https://user-images.githubusercontent.com/8235763/29942053-d8d613e0-8e94-11e7-99a8-2ccdb408eeca.jpg)
Settings in options:
![bildschirmfoto 2017-08-31 um 21 39 41](https://user-images.githubusercontent.com/8235763/29942086-ec164f1a-8e94-11e7-99b7-89e867e0ff70.jpg)
Change Float in Options Images in Weblinks float like setting in Options. This works only with second Image, first Image stay always like "none".

But this is a different Question as i'm on double Fieldname which should be different.

**Comment by franz-wohlkoenig** [comment]
closed as having Pull Request #376
