### ISSUE TITLE
Fatal error when building the package.

### ISSUE THREAD

**Issue by soap** [joomla-extensions/weblinks#361]
### Steps to reproduce the issue
Run "vendor\bin\robo build" in cli.

### Expected result
The package was successfully built.

### Actual result
Fatal error: Uncaught Error: Call to a member function newBuilder()  D:\Joomla Projects\weblinks\vendor\consolidation\robo\src\Common\BuilderAwareTrait.php:43

### System information (as much as possible)
Windows 10 with PHP 7.0.3

### Additional comments
Before upgrade to the latest update its works fine.

**Comment by 810** [comment]
got it working on my pr, we need only a travis fix.

**Comment by soap** [comment]
@810 Sorry but you mean using your pull request branch, it is ok. What is your OS and PHP version?

**Comment by soap** [comment]
Ok I found the cause of problem in RoboFile.php; method getExecutableExtension(). If I not call` if (!$this->_exec('git.exe --version')->getMessage())` and immediately return '', it works.

**Comment by astridx** [comment]
@soap and @810 Can we close this issue as you found the solution?

**Comment by Bakual** [comment]
Nope, as the issue still exists.
I stumbled over the same problem. I wonder why that method even exists.

**Comment by Bakual** [comment]
I tried to fix it with https://github.com/joomla-extensions/weblinks/pull/381
That one worked for me, allthough I don't know if the whe method is even needed.

**Comment by joomdonation** [comment]
I just built the package myself and it worked. So I guess the issue was fixed elsewhere and close this issue. Feel free to re-open if you still get the issue. Thanks !
