### ISSUE TITLE
A question about composer.json

### ISSUE THREAD

**Issue by astridx** [joomla-extensions/weblinks#364]
Is there a reason why we use 
[joomla-browser version 3.6.5.1 ](https://github.com/joomla-extensions/weblinks/blob/84a98f9718a4dbecc3f1447839baa040c460b3e8/composer.json#L15)
and 
[Selenium Server Standalone 3.1.0``](https://github.com/joomla-extensions/weblinks/blob/84a98f9718a4dbecc3f1447839baa040c460b3e8/composer.json#L18)?
Or can we use the current versions 
[joomal-browser 3.7.5](https://github.com/joomla-projects/joomla-browser/releases)
and 
[Selenium Server Standalone 3.5.2](https://github.com/joomla-projects/selenium-server-standalone/releases)

**Comment by 810** [comment]
see my pr, we need only a fix for travis, i can't get travis working. Local is working fine.

**Comment by astridx** [comment]
Thank you @810

**Comment by yvesh** [comment]
Did you Firefox @810, went into multiple issues which were Chrome related.

**Comment by 810** [comment]
Firefox is not working at all, and on chrome i got at point: "Field by name, label, CSS or XPath element with '#jform_language' was not found."

And on local, chrome is the only one working
