### ISSUE TITLE
Tags are deleted if Ordering by Drag an Drop is used

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla-extensions/weblinks#368]
### Steps to reproduce the issue

- use Tags on Weblinks
- at `/index.php?option=com_weblinks&view=weblinks` click on first Column "Ordering" and move per Drag and Drop one Weblink above another
- Tags on both Weblinks are deleted
### Test on
- weblinks-3.6.0
- macOS Sierra, 10.12.5
- Firefox 56.0 (64-bit)
- PHP 7.0.4
- MySQLi  5.5.57-0+deb7u1

**Comment by brianteeman** [comment]
That suggests that the tag is being associated to the orderid and not the recordid which would be wrong. i cant think of any other reason

**Comment by Puckmeister** [comment]
The same problem also exists when tags are used in com_content, so it's not only about com_weblinks. (https://github.com/joomla/joomla-cms/issues/18317)

**Comment by brianteeman** [comment]
That guess was wrong - it is worse than I thought.
As soon as you reorder the weblink the record in the #__contentitem_tag_map table is deleted

**Comment by franz-wohlkoenig** [comment]
closed as having Pull Request [#18328](https://github.com/joomla/joomla-cms/pull/18328)
