### ISSUE TITLE
jed_update.xml - Do we need this file?

### ISSUE THREAD

**Issue by astridx** [joomla-extensions/weblinks#369]
I read, that  the update the JED XML update feature is not live yet. 

For what do we need the file jed_update.xml ?

**Comment by zero-24** [comment]
No. As it does not work yet but it can serve as example ;-)

**Comment by astridx** [comment]
I believe that it confuses people rather - just like me ...

**Comment by zero-24** [comment]
https://github.com/joomla-extensions/weblinks/pull/370 😄 Feel free to merge
