### ISSUE TITLE
I can not create a web link with the same alias in different languages. 

### ISSUE THREAD

**Issue by astridx** [joomla-extensions/weblinks#371]
### Steps to reproduce the issue
Create an article with the alias welcome for the language English and German.

### Expected result
This should be possible

### Actual result
It is not possible. You get a warning because of duplicated alias. (Save failed with the following error: There is already a Web Link with that name in this category. Please try again.)

### Additional comments
This is an issue after adding the single view and the multilingual associations: https://github.com/joomla-extensions/weblinks/pull/349

**Comment by astridx** [comment]
Close as there is PR https://github.com/joomla-extensions/weblinks/pull/373

**Comment by franz-wohlkoenig** [comment]
> Create an article with the alias welcome for the language English and German.

You mean "Create an weblink with the alias welcome for the language English and German."?

**Comment by astridx** [comment]
@franz-wohlkoenig Thank you. I have corrected it.
