### ISSUE TITLE
Web Link- Edit: Meta information on Publisching tab, not on Metadata tab

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla-extensions/weblinks#388]
### Steps to reproduce the issue
Go to Components - Web Links and select a Web LINK.
Go to tab Publishing.

### Expected result
No meta information (must be on Metadata tab)

### Actual result

Meta Description 
Meta keywords
External Reference
Robots
Content Rights

The last two are on Metadata tab also (duplicate)
### System information (as much as possible)
Joomla 3.8.7

**Comment by joomdonation** [comment]
Closing because:

- It works in the same way with other core components
- And we do not have Metadata tab

Maybe it was an issue with old version but as of right now, this issue is invalid to me.
