### ISSUE TITLE
[4.0-dev] Getting 404 Component not found on Joomla! 4.0.0-alpha6-dev

### ISSUE THREAD

**Issue by manojLondhe** [joomla-extensions/weblinks#392]
### Steps to reproduce the issue

- I was checking out today, `4.0-dev` branch code on `Joomla! 4.0.0-alpha6-dev`
- Managed to discover-install
- However,accessing links view in backend shows 404 error

Call stack
--

 |      |   Function	 |   Location |  
 |----------|:-------------|:------|
 |   1	 |   ()  |   JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:59  |   
 |   2	 |   Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() |   ROOT/libraries/src/Component/ComponentHelper.php:380 |  
 |   3	 |   Joomla\CMS\Component\ComponentHelper::renderComponent() |   ROOT/libraries/src/Application/AdministratorApplication.php:116 |  
 |   4	 |   Joomla\CMS\Application\AdministratorApplication->dispatch() |   ROOT/libraries/src/Application/AdministratorApplication.php:159 |  
 |   5	 |   Joomla\CMS\Application\AdministratorApplication->doExecute() |   ROOT/libraries/src/Application/CMSApplication.php:233 |  
 |   6	 |   Joomla\CMS\Application\CMSApplication->execute()	 |   JROOT/administrator/includes/app.php:63  |  
 |   7	 |   require_once()	 |   JROOT/administrator/index.php:36  |  

- Database Type	mysql
- Database Version	5.7.24-0ubuntu0.16.04.1
- Database Collation	utf8mb4_unicode_ci
- Database Connection Collation	utf8_general_ci
- PHP Version	7.2.12-1+ubuntu16.04.1+deb.sury.org+1
- Web Server	Apache/2.4.37 (Ubuntu)
- WebServer to PHP Interface	fpm-fcgi
- Joomla! Version	Joomla! 4.0.0-alpha6-dev Development [ Amani ] 4-November-2018 23:23 GMT

--

**Comment by wilsonge** [comment]
Some of this is fixed now in the branch after https://github.com/joomla-extensions/weblinks/commit/828325e86ca2fa6b59225d32a275b1ea41170bb6
