### ISSUE TITLE
line including title and alias is not wrapped, table width is increased instead

### ISSUE THREAD

**Issue by kofaysi** [joomla-extensions/weblinks#395]
### Steps to reproduce the issue

Create weblink with a title of 200+ characters

### Expected result

The Title (Alias) line to be wrapped in /administrator/index.php?option=com_weblinks view

### Actual result

The Title (alias) line is not wrapped and the table width of the weblink list is increased. Columns Access, Hits, Language and ID are behind the right screen (scrolling is required).

### System information (as much as possible)

Joomla! 3.9.2

**Comment by kofaysi** [comment]
The `nowrap` class is causing the cell width to enlarge to the content.
https://github.com/joomla-extensions/weblinks/blob/8574a4f3cfc9c2976cea10bda12d8de49967f84c/src/administrator/components/com_weblinks/views/weblinks/tmpl/default.php#L127

**Comment by joomdonation** [comment]
Closing this because the issue was fixed with this PR https://github.com/joomla-extensions/weblinks/pull/401
