### ISSUE TITLE
Make release Web Links 3.7.0 or 3.8.0-beta

### ISSUE THREAD

**Issue by yozmag** [joomla-extensions/weblinks#396]
### Steps to reproduce the issue
Install version Web Links 3.7.0-beta1

### Expected result
Expected new feature, like menu type show weblink 

### Actual result
This new feature has been submitted on 3 Nov 2017 but it isn't release.

### Additional comments
Please make a new release with all new commits since 3.7.0-beta1.

**Comment by zero-24** [comment]
https://github.com/joomla-extensions/weblinks/releases/tag/3.7.0

**Comment by yozmag** [comment]
Thank you this is resolved.
