### ISSUE TITLE
[META] Deprecate/Abandon package

### ISSUE THREAD

**Issue by mbabker** [joomla-extensions/weblinks#398]
As demonstrated by the lack of activity on this repository from a management perspective, the extension package is effectively abandonware at this point.  Therefore, I propose to formally recognize the status quo and deprecate support for the package as a Joomla owned resource.  If a community resource would like to pick up maintenance then so be it, but the Joomla project clearly does not have the resources required to support this package as a standalone tool.

//cc @wilsonge @HLeithner

**Comment by HLeithner** [comment]
Is it really abandon? Allon already tested the upgrade to J4. Do you really want to drop com_weblinks, especially as it could be  a good example how to upgrade components from j3 to j4?

btw. we have as similar problem with j4 unit tests.

**Comment by mbabker** [comment]
If it's going to be maintained then this can be closed.  The problem is this package is not being maintained at all.  The last release was a beta 21 months ago, there look to be several bug fixes incorporated since then, and support for custom fields added.  Either resources need to be dedicated to ensuring it gets routine maintenance, or the package refolded into the main CMS repo if it is too difficult to maintain a standalone production tool, or the project abandon it given a lack of resources and a third party can pick it up if desired.

**Comment by carcam** [comment]
What can I do to be part of the support of this package?

**Comment by HLeithner** [comment]
@carcam Simple check all issues and PRs. Make comments on them and if needed create a new pr to fix them.

And in the longterm take the maintainer role for this and maybe for other joomla "core" extensions. 

That would be great.

One bigger step ist to migrate com_weblinks to j4 (allon started already).

If you have question don't hesitate to ask.

**Comment by mbabker** [comment]
Typical, take no action on something that clearly needs action.  What a joke.
