### ISSUE TITLE
3.4.1-rc SQL error

### ISSUE THREAD

**Issue by zero-24** [joomla-extensions/weblinks#40]
`Duplicate column name 'version' SQL=ALTER TABLE `p52jk_weblinks` ADD COLUMN `version` int(10) unsigned NOT NULL DEFAULT '1';`

Update Joomla 3.3.6 to 3.4.1 upload and install the RC package.

I guess we need something like for the drop colums also for the add colums?

**Comment by wilsonge** [comment]
See #41
