### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by BrunnoPrego** [joomla-extensions/weblinks#400]
### Steps to reproduce the issue
Follow the steps to test de component

### Expected result
Build the test cases (robo build)

### Actual result
Getting errors in composer install:

Deprecation warning: require-dev.Behat/Gherkin is invalid, it should not contain uppercase characters. Please use behat/gherkin instead. Make sure you fix this as Composer 2.0 will error.

and

Package joomla-projects/robo is abandoned, you should avoid using it. Use joomla-projects/joomla-testing-robo instead.

and 

PHP Fatal error:  Uncaught Error: Call to a member function newBuilder() on null in C:\xampp\htdocs\runweblinks\weblinks\vendor\consolidation\robo\src\Common\BuilderAwareTrait.php:44

### System information (as much as possible)
Possibily any system will get this, but I tryed in xampp on windows 10 with git-bash

### Additional comments
None
[shellout.txt](https://github.com/joomla-extensions/weblinks/files/3097845/shellout.txt)

**Comment by wilsonge** [comment]
Fixed with https://github.com/joomla-extensions/weblinks/commit/a012bc7b63176dfb51ba2586dcaf02c4fed98133
