### ISSUE TITLE
[3.7.0] Is there a reason we not push 3.7.0 over the update server

### ISSUE THREAD

**Issue by zero-24** [joomla-extensions/weblinks#408]
There is a 3.7.0 release but the update server has not been updated yet and still points to 3.6.0: https://github.com/joomla-extensions/weblinks/blob/master/manifest.xml

is there any reason? I'm happy to send a PR when not.

**Comment by wb7** [comment]
I am also interested in this reason, if there is something blocking an update.

**Comment by zero-24** [comment]
@wilsonge @yvesh @HLeithner can you check this here?

**Comment by wilsonge** [comment]
Yes. Because when I did it I didn't get round to figuring out how to upload the binary to the downloads site. Which is required to push the version out. Then amongst my holiday and other things I forgot about it. It needs to be uploaded to the downloads site before the update site gets updated

**Comment by mbabker** [comment]
> It needs to be uploaded to the downloads site before the update site gets updated

Log into AWS directly and upload files there.  Since the upload function was removed from the component that's been the workflow.

**Comment by wilsonge** [comment]
Done! thanks for the pointer guys (i dropped off releases before aws)
