### ISSUE TITLE
Confirm about javascript in J4 branch

### ISSUE THREAD

**Issue by wilsonge** [joomla-extensions/weblinks#409]
@dgrammatiko can i confirm that the code I commented out in https://github.com/joomla-extensions/weblinks/commit/2be3dec52abbddf807cd9e1d83399327ec4911f9 is no longer required?

**Comment by dgrammatiko** [comment]
Yes, you’re right is not required as long as the form has a class `form-validate` which is the case in that page

**Comment by wilsonge** [comment]
Thanks!

**Comment by richard67** [comment]
@wilsonge Can this be closed after last commit [https://github.com/joomla-extensions/weblinks/commit/25fa454c985be7e024b68d18f9da8ad9f119ee6a](https://github.com/joomla-extensions/weblinks/commit/25fa454c985be7e024b68d18f9da8ad9f119ee6a) to the 4.0-dev branch?

**Comment by wilsonge** [comment]
Code needs to be deleted rather than just commented out. After that yes

**Comment by wilsonge** [comment]
Oh i already did delete it and you linked to it 🤦‍♂
