### ISSUE TITLE
Inconsistent PHP minimum version

### ISSUE THREAD

**Issue by mbabker** [joomla-extensions/weblinks#411]
The Composer manifest lists PHP 5.4 as the minimum PHP version, yet the extension script file checks the Joomla minimum (5.3.10) as the minimum PHP version.  The PHP minimum should be consistent.

**Comment by zero-24** [comment]
Please check this PR: https://github.com/joomla-extensions/weblinks/pull/412

**Comment by richard67** [comment]
Can this be closed now after #412 has been merged?
