### ISSUE TITLE
Custom fields backend interface is broken in  3.7.0

### ISSUE THREAD

**Issue by HLeithner** [joomla-extensions/weblinks#413]
### Steps to reproduce the issue
Install 3.7.0
Click on custom fields, submenu is missing.

### Expected result
See the complete submenu.

### Actual result
See no submenu

### System information (as much as possible)
j 3.9.11

**Comment by zero-24** [comment]
hmm it is working totally fine to me:
![image](https://user-images.githubusercontent.com/2596554/64899873-d42d9280-d68d-11e9-9281-cc6d95c03632.png)

Just installed a fresh 3.9.11 and the latest weblinks.

**Comment by zero-24** [comment]
Maybe you still run a version without this core patch: https://github.com/joomla/joomla-cms/commit/360ae810303aab714ed2214f5a1dd438c330bd9c ?

**Comment by HLeithner** [comment]
I used a testing site so it's possible it's broken in some way but I reinstalled joomla with the updater... I will check on another site but george didn't replicate it too. So I think it's fine

**Comment by bembelimen** [comment]
Worked for me: 3.6 to 3.7
System info:
![grafik](https://user-images.githubusercontent.com/1229869/64909939-139dc280-d712-11e9-84e7-e30cde57d085.png)

**Comment by HLeithner** [comment]
Ok I checked it again and @zero-24 is right both installation as used a buggy 3.9.11 test installation...
