### ISSUE TITLE
missing button [Associations] for created links

### ISSUE THREAD

**Issue by universewrld** [joomla-extensions/weblinks#419]
### Steps to reproduce the issue

1. Create and **save** the link in any language (for example: `en-GB`).
2. After that, you will not see button `Associations`, but it should be.

### Expected result
![изображение](https://user-images.githubusercontent.com/3662519/75096401-5bbdec80-55b0-11ea-838a-d00dae01390f.png)

### Actual result
![изображение](https://user-images.githubusercontent.com/3662519/75096438-a5a6d280-55b0-11ea-9dd0-2e7bbb02b385.png)

### System information (as much as possible)
Joomla 3.9.15, Web Links 3.7.0, PHP 7.3.9, MySQL 5.5.5-10.3.13-MariaDB-log

### Additional comments
See also: [https://github.com/joomla-extensions/weblinks/issues/418](https://github.com/joomla-extensions/weblinks/issues/418)

**Comment by infograf768** [comment]
Replace the file `/administrator/components/com_weblinks/views/weblink/view.html.php` by this one, once uncompressed.
[view.html.php.zip](https://github.com/joomla-extensions/weblinks/files/5011938/view.html.php.zip)

Also please confirm patch there and once done please close this isssue
https://github.com/joomla-extensions/weblinks/pull/426

**Comment by joomdonation** [comment]
There is PR https://github.com/joomla-extensions/weblinks/pull/426 which solves this issue, so I'm closing this issue.
