### ISSUE TITLE
tags display in category view

### ISSUE THREAD

**Issue by mc-cm** [joomla-extensions/weblinks#420]
Hi!
Don't really know if I'm at the right place to report a bug / inconsistency in the existing com_weblinks component.

### Steps to reproduce the issue
- Set the general settings of com_weblinks to "category ->display tags: yes" (last option)
- Create a menu item showing a single category of weblinks (index.php?option=com_weblinks&view=category&id=24)
### Expected result
The tags of the category should be visible (somewhere beneath the discription?)
### Actual result
No tags are displayed. At least I can't make the visible, even not via template override.
### System information (as much as possible)
- Linux lap-arch-cm 5.5.9-arch1-2 #1 SMP PREEMPT Thu, 12 Mar 2020 23:01:33 +0000 x86_64
- php 7.4.3
- Joomla! 3.9.14 Stable
- com_weblinks 3.7.0

### Additional comments
Thank you for your attention

**Comment by joomdonation** [comment]
![category](https://user-images.githubusercontent.com/977664/129867039-cc968c95-0587-4997-9b9e-134ca5bd0784.png)

Tags are now being displayed with the latest commits, see the above screenshot. So I'm closing this issue.
