### ISSUE TITLE
Web Links Extension Package needs targetplatform tag

### ISSUE THREAD

**Issue by bayareajenn** [joomla-extensions/weblinks#421]
### Steps to reproduce the issue
Install Joomla 3 plain/core only site
Add Weblinks component
Set it to update to Joomla 4 nightly builds (Options -> Custom URL-> Development -> https://update.joomla.org/core/nightlies/next_major_list.xml
Save & Close 
Check the Pre-Update Check Extension Tab
Weblinks shows as "No" in the Compatible column
![Weblinks-No](https://user-images.githubusercontent.com/5952595/83066661-02d87700-a02b-11ea-9ef6-36d8d8b9c8ac.jpg)
Then migrate to Joomla 4 and it DOES migrate with the click through.

### Expected result
Should say "Yes" that it is compatible with J!4

### Actual result
It says that it doesn't but it does work on the one-click.

### System information (as much as possible)
n/a

### Additional comments
 I think just the tag is missing to say "Yes."

**Comment by HLeithner** [comment]
The installed version is 3.7.0, this version is not prepared for j4. For example the backend interface should be broken.

**Comment by bayareajenn** [comment]
> 
> 
> The installed version is 3.7.0, this version is not prepared for j4. For example the backend interface should be broken.

Darnit. I made a mistake. Won't be the last mistake I make I'm sure. I'm going to close this out and I'll talk to George in the update working group about it. Thanks Harald. :)
