### ISSUE TITLE
[3.7.0] Count / Countable bug in PHP 7.4+

### ISSUE THREAD

**Issue by LuxLOL** [joomla-extensions/weblinks#422]
### Steps to reproduce the issue

Installing the WebLinks extension. And creating a Joomla menu to a Web Link.
https://downloads.joomla.org/extensions/weblinks
This happens also with the WebLinks Module.

### Expected result

No errors in the HTTP Server log.

### Actual result

PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/clients/client1/web17/web/components/com_weblinks/models/categories.php on line 95
PHP Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/clients/client1/web17/web/modules/mod_weblinks/mod_weblinks.php on line 17

### System information (as much as possible)

Joomla v3.9.19 with PHP v7.4 (fpm-fcgi) and MySQL v5.5.5

### Additional comments

Forum Topic link: https://forum.joomla.org/viewtopic.php?f=715&t=980815

**Comment by ReLater** [comment]
PR only for the module issue (confirmed with Joomla 3.9.x): https://github.com/joomla-extensions/weblinks/pull/432

**Comment by joomdonation** [comment]
Fixed in latest codebase and will be included in next release. So I'm closing this issue.
