### ISSUE TITLE
Feature request: option for adding website thumbshots / thumbnails

### ISSUE THREAD

**Issue by pod-o-mart** [joomla-extensions/weblinks#430]
There are services like [bitpixels](https://www.bitpixels.com) or [Easy-Thumb](https://www.easy-thumb.net/en/index.html) that provide thumbnails for urls. Would be a nice thing if there was an option in the component where one could add the  string of a service in order to have the thumbnail of each corresponding weblink displayed.

E.g. when I want to use thumbnails from [Easy-Thumb](https://www.easy-thumb.net/en/index.html) I'd add the string `https://www.easy-thumb.net/thumb?url=` to the input field in the configuration of the component. Consequently the weblinks component would embed thumbnails next to each weblink.

The result could look like in here: https://oesteuropastudier.dk/en/tools/digital-humanities (this example is based on an override by me, though).

As most free thumbnail providers require a backlink, there should also be an additional textfield for it in weblink/category view.

**Comment by joomdonation** [comment]
As of right now, we do not have plan for supporting this feature, sorry. So I'm closing this issue.
