### ISSUE TITLE
Support for Joomla 4

### ISSUE THREAD

**Issue by Lovntola** [joomla-extensions/weblinks#431]
### Steps to reproduce the issue
Install Weblinks on Jommla 3.x
Upgrade to Joomla 4 Alpha 6

### Expected result

If you select the Component / Web Links / Links You can see all Weblinks and can edit like under Jo0mla 3 

### Actual result
If you select the Component / Web Links / Links
There come a Error Message
`500  behavior::tabstate not found.`

### System information (as much as possible)

Upgrade to Joomla 4 Alpha 6

**Comment by alikon** [comment]
there is a branch https://github.com/joomla-extensions/weblinks/tree/4.0-dev for the j4 version

**Comment by Lovntola** [comment]
Oh, sorry I din't see that.
I will close this Issue
