### ISSUE TITLE
Installing pkg_weblinks_3.4.1-rc.zip on a legacy site

### ISSUE THREAD

**Issue by infograf768** [joomla-extensions/weblinks#44]
I tried installing the package on a legacy site updated to 3.4.2-dev (i.e. weblinks still present).
I get these errors:
```

Warning

Duplicate column name 'version' SQL=ALTER TABLE `jos_weblinks` ADD COLUMN `version` int(10) unsigned NOT NULL DEFAULT '1';

Package Update: There was an error installing an extension: com_weblinks.zip
Error

Error installing package
```

**Comment by infograf768** [comment]
Oops, duplicate of https://github.com/joomla-extensions/weblinks/issues/40
closing.

**Comment by zero-24** [comment]
@infograf768 can you try: [pkg_weblinks341_with_fixes](http://www.jah-tz.de/downloads/download.php?file=pkg_weblinks_3.4.1-rc.zip&folder=media/joomla/) 

It combined both fixes: https://github.com/joomla-extensions/weblinks/pull/42 and https://github.com/joomla-extensions/weblinks/pull/43

Thanks :smile:

**Comment by infograf768** [comment]
That pack works fine, no more error.

**Comment by zero-24** [comment]
Thanks @infograf768 !

**Comment by javigomez** [comment]
@test works here too
