### ISSUE TITLE
[4.0] Cannot move Weblinks to Joomla 4

### ISSUE THREAD

**Issue by obuisard** [joomla-extensions/weblinks#446]
### Steps to reproduce the issue

Install Joomla 3.10 with Weblinks.
Migrate to Joomla 4.
The Weblinks component breaks.

### Expected result

Able to create web links.

### Actual result

Error 500
![weblinks_issue](https://user-images.githubusercontent.com/5964177/129543526-1f284799-627f-41b8-91b4-e36d8549a001.png)

### System information (as much as possible)

PHP 7.3.11 Apache 2.4.41 MySQL 5.7.14
Joomla 3.10 RC2 to Joomla 4 RC6

**Comment by alikon** [comment]
take a look at this one https://github.com/joomla-extensions/weblinks/pull/436

**Comment by obuisard** [comment]
> take a look at this one #436

Thank you! I missed it :-)

**Comment by joomdonation** [comment]
@obuisard Here is the weblinks package from latest code in that PR. If you have sometime, please help testing it and update us with the result. Thanks. 
[pkg-weblinks-4.0.0-dev.zip](https://github.com/joomla-extensions/weblinks/files/6991840/pkg-weblinks-4.0.0-dev.zip)

**Comment by obuisard** [comment]
> @obuisard Here is the weblinks package from latest code in that PR. If you have sometime, please help testing it and update us with the result. Thanks.
> [pkg-weblinks-4.0.0-dev.zip](https://github.com/joomla-extensions/weblinks/files/6991840/pkg-weblinks-4.0.0-dev.zip)

Yes, I will try the package later today, thank you!

**Comment by joomdonation** [comment]
Thanks @obuisard

**Comment by richard67** [comment]
Closing as having a pull request.
