### ISSUE TITLE
[4.0] param show_cat_num_links_cat or show_cat_num_links ?

### ISSUE THREAD

**Issue by chmst** [joomla-extensions/weblinks#463]
### Steps to reproduce the issue
https://forum.joomla.de/thread/14353-com-weblinks-ist-f%C3%BCr-version-3-und-4-neu-freigegeben/?postID=93269#post93269

param for number of links is set but not displayed

### Expected result
Number of links is shown in view categories

### Actual result
Number is missing 

### System information (as much as possible)
https://forum.joomla.de/thread/14353-com-weblinks-ist-f%C3%BCr-version-3-und-4-neu-freigegeben/?postID=93269#post93269

**Comment by joomdonation** [comment]
Guess it causes by your copy/paste error while working on the layout. Could you please check and confirm this commit https://github.com/joomla-extensions/weblinks/commit/8aa92f906b7ea2740b245bbc999a6cf304528d0f fixed it?

**Comment by chmst** [comment]
https://github.com/joomla-extensions/weblinks/blob/master/src/administrator/components/com_weblinks/config.xml#L316 it was caused from here. The two models for category and categies use different filters. So we should decide which name we use everywhere.

**Comment by joomdonation** [comment]
The `Categories` model should use **show_cat_num_links_cat** parameter. The Category model will use **show_cat_num_links** parameter. That's same with how other core components work.

**Comment by Sieger66** [comment]
> 
> 
>  Could you please check and confirm this commit [8aa92f9](https://github.com/joomla-extensions/weblinks/commit/8aa92f906b7ea2740b245bbc999a6cf304528d0f) fixed it?

For me it fix it. Thank you.
