### ISSUE TITLE
[reminder][J4.1] creation date in xml

### ISSUE THREAD

**Issue by chmst** [joomla-extensions/weblinks#470]
### Steps to reproduce the issue
If this PR https://github.com/joomla/joomla-cms/pull/27162 passes for 4.1 com_weblinks xhould change the create date in the manifest file.

**Comment by joomdonation** [comment]
The build script which is used to build weblinks package generate the date in expected format for creation date, so we do not have to do anything ourself. Weblinks is compatible with that feature out of the box :).
