### ISSUE TITLE
Lins which open as popup window must be underlined or styled as button

### ISSUE THREAD

**Issue by chmst** [joomla-extensions/weblinks#476]
### Steps to reproduce the issue
Links must be underlined. 
If a weblink opens in a modal, the link is a button and not underlined

### Expected result

The link, opening in a pop-up looks like a button or it is underlined

### Actual result

![image](https://user-images.githubusercontent.com/1035262/145635511-0fb9b1cd-fba7-4090-8a70-b0764f61fd71.png)

**Comment by joomdonation** [comment]
@chmst Could you please make PR to solve this issue?

**Comment by chmst** [comment]
Please test #512
