### ISSUE TITLE
component global target parameter doesn't work in module

### ISSUE THREAD

**Issue by dolmenhir** [joomla-extensions/weblinks#477]
Global target status set in the component's parameters do not work on module:

- if the global target parameter is set on "new window" links are opened in "parent window" from the "web links" module.

note: that works if target is set inside the link parameters.

### System information (as much as possible)
Joomla 3.10.3
Component/module version : web links 3.9.0
Php 7.4.x and 8.x

**Comment by joomdonation** [comment]
@dolmenhir Sorry for lately response. I was having some family stuff and could not work much as usual. Please install this updated package of the extension to your site, that should address the issue you are having

[pkg-weblinks-3.9.0.zip](https://github.com/joomla-extensions/weblinks/files/7761102/pkg-weblinks-3.9.0.zip)
