### ISSUE TITLE
remove weblink packages

### ISSUE THREAD

**Issue by SerGun78** [joomla-extensions/weblinks#478]
Hey! When the package is deleted, the link to the categories remains in the components.
![изображение](https://user-images.githubusercontent.com/95705148/146001756-76329d9f-d20a-4027-8d7c-9254100b5eeb.png)

**Comment by joomdonation** [comment]
I could not re-procedure the issue myself. In your case, I guess the uninstall was not success for some reasons (the data in #__menu table is broken)

A dirty solution for this issue could be delete the menu item record manually from #__menu (via phpmyadmin).

**Comment by chmst** [comment]
@SerGun78 I think that this is resolved and close the issue.
