### ISSUE TITLE
[4.0.1] Weblinks editor button fails.

### ISSUE THREAD

**Issue by ReLater** [joomla-extensions/weblinks#479]
2 users in german forum reported an issue with TinyMce and editor weblinks button plugin and I can confirm it. (Also JCE editor displays a JS error.)

Post https://forum.joomla.de/thread/14215-com-weblinks-joomla-4-0-2/?postID=98377#post98377 et seq.

### Steps to reproduce the issue
- Joomla 4.0.5 migratet from Joomla 3.10.3 inclusive weblinks package and afterwards updated weblinks package (as far as I remember).
- Activate editor button plugin ("Button - Web Link").
- Edit an article. I was in backend.
- Try to insert a weblink link via editor button "Web Link".
- PopUp with `com_weblinks` links opens.
- Select a link.

### Expected result
- Inserts weblink link in editor text and closes popup/modal

#### With JCE editor:

Link is inserted in editor text but popup/modal doesnt't close automatically.

`Uncaught TypeError: window.parent.jModalClose is not a function (admin-weblinks-modal.min.js:1:475)`

### With TinyMce

Nothing happens at all. No link in editor text. Modal doesn't close

`Uncaught TypeError: window.parent.jInsertEditorText is not a function (admin-weblinks-modal.min.js:1:438)`

**Comment by ReLater** [comment]
### Solution:
Minified `admin-weblinks-modal.min.js` contains outdated code (from Joomla 3).

After minifying `admin-weblinks-modal.js` newly in Visual Code the button works correctly.

**Comment by joomdonation** [comment]
Thanks @ReLater . I will take a look at it on tomorrow.

**Comment by joomdonation** [comment]
Confirmed the issue and solution. If anyone is having this issue, please use this updated package (while waiting for new version). Thanks again for looking at the issue and suggest the solution @ReLater . 

[pkg-weblinks-4.0.1.zip](https://github.com/joomla-extensions/weblinks/files/7754989/pkg-weblinks-4.0.1.zip)
