### ISSUE TITLE
Since staging branch doesn't exists anymore in joomla cms repo it's breaking drone build requiring joomla staging branch

### ISSUE THREAD

**Issue by alexandreelise** [joomla-extensions/weblinks#490]
### Steps to reproduce the issue
Try to do a pull request on master branch of joomla-extensions/weblinks 
without changing RoboFile.dist.ini branch setting from staging to an branch that exist in joomla/joomla-cms repo.

### Expected result
drone ci continues after cloning the correct repo

### Actual result
drone ci stops and breaks when trying to clone staging branch from joomla cms which doesn't exists anymore.

### System information (as much as possible)
irrelevant since it happens on drone ci server

### Additional comments
Since staging branch doesn't exists anymore in joomla cms repo it's breaking drone build requiring joomla staging branch.
By default when branch is set to staging or when it's not set at all in the code it fallback to staging branch which breack drone builds expecting staging branch when cloning joomla cms for the tests.

The solution that might work is to choose a specific branch related to the joomla version the weblinks extension repo is targeting.For example. If master branch of weblinks is for 4.1-dev, set this branch to 4.1-dev
https://github.com/joomla-extensions/weblinks/blob/fc2d0f493879a5c62f3f9bfd7ae13ea5b16f172c/RoboFile.dist.ini#L10
Same thing for 3.10-dev branch and 4.0-dev branch. You get the idea. Hopefully it make sense.
Need your feedback. @wilsonge @zero-24 @bembelimen

**Comment by zero-24** [comment]
Sounds like a good idea. Cc @joomdonation 

When there are still issues maybe @Hackwar can help on the drone setup? As I'm far way of beeing an expert there :-)

**Comment by Hackwar** [comment]
Since the test setup has been updated for 4.0 now, I'm closing this issue.
