### ISSUE TITLE
Deprecated message when adding a new weblink in Backend 

### ISSUE THREAD

**Issue by chmst** [joomla-extensions/weblinks#511]
### Steps to reproduce the issue
On a installation with PHP 8.1 open the "new,weblink" form. 

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /libraries/vendor/joomla/registry/src/Format/Json.php on line 54

### System information (as much as possible)
Joomla 4.2.2,  weblinks component 4.0.1, PHP Version 8.1.6

**Comment by joomdonation** [comment]
Thanks. Fixed with this commit https://github.com/joomla-extensions/weblinks/commit/b3953c554cae7a6d3999117b7350f1f2c702d097
