### ISSUE TITLE
How to upgrade to Joomla 4

### ISSUE THREAD

**Issue by ramblerswebs** [joomla-extensions/weblinks#521]
When I run the Pre-Update Check for Joomla 4.2.9 it tells me that I should update the Weblinks extension BEFORE upgrading to Joomla 4
But I am running the latest J3 version 3.9.0 and looking at the manifest file the next version 4.0.1 is only set up for J4
so is this a catch 22 so cannot update to J4

**Comment by chmst** [comment]
You can run an update on weblinks after the upgrade of Joomla.

**Comment by ramblerswebs** [comment]
Shouldn't it say that somewhere.
Weblinks appears in the section Please update these extensions before updating Joomla.

I'm not a programmer so don't understand these things

**Comment by richard67** [comment]
Closing as expected behaviour. I agree the section heading might be misleading, but that's not an issue with weblinks, it's an issue with the pre-update check of the CMS.

You have to wait until #524 is merged before you will find the weblinks update on a Joomla 4.3.x.
