### ISSUE TITLE
J5a4 - Weblinks is broken in J5. Requires b/c plugin to install and function. 

### ISSUE THREAD

**Issue by bayareajenn** [joomla-extensions/weblinks#532]
### Steps to reproduce the issue

1. Create a J5 test site (nightlies).
2. Download and install weblinks.
3. You'll see an "internal server error" warning and the extension will not install.
4. Go to System -> Plugins and enable the Behaviour - Backward Compatibility Plugin.
5. Install weblinks and you'll be able to install the extension and it will function.

### Expected result
As an "official Joomla extension", the Weblinks extension should install and function with the b/c plugin disabled. 

### Actual result
The Weblinks extension will not install nor function if the b/c plugin is disabled.

### System information (as much as possible)
Use the nightlies for J5.
PHP 8.1
MySQL 8.0.x
FF

**Comment by joomdonation** [comment]
Hi @bayareajenn 

Today, we released version 4.3.0 https://github.com/joomla-extensions/weblinks/releases/tag/4.3.0 which works well with Joomla 5.0 without requiring Backward Compatibility plugin, so I'm closing this issue.

**Comment by bayareajenn** [comment]
Thank you Tuan! Just tested it without (and with) the b/c plugin and it's working great with all I've tested. Thank you!!! <3

**Comment by bayareajenn** [comment]
Any chance the listing on the JED could be updated? I'd like to link it from the J4 to J5 upgrade doc. https://extensions.joomla.org/extension/weblinks/

**Comment by joomdonation** [comment]
Thanks @bayareajenn for testing. Yes, I am asking for help from someone to update the listing on JED. Should be updated soon !
