### ISSUE TITLE
Division Not Closed in a /mod_weblinks/tmpl/ File

### ISSUE THREAD

**Issue by cmbr** [joomla-extensions/weblinks#533]
A closing HTML division tag is missing from the _/modules/mod_weblinks/tmpl/default.php_ file in the **4.0-dev branch**.
The division with the classes _d-flex_ and _flex-wrap_ opens at or near line 59 but is never closed.

### Steps to reproduce the issue
To test, create a module using this extension in a Joomla 4.3.3 website. Include at least one weblink. The web page on which it is displayed will not pass an HTML validator. For each weblink displayed, the validator will report two errors:
_Error: End tag li seen, but there were open elements._
_Error: Unclosed element div._

### Additional comments
The solution is to add a `</div>` tag just before the `</li>` tag at or near line 183 of the _/modules/mod_weblinks/tmpl/default.php_ file.

**Comment by alikon** [comment]
@cmbr can you submit a pull request ?

**Comment by cmbr** [comment]
Yes, as soon as someone makes me a collaborator here. My attempt at creating a pull request was blocked.

**Comment by Hackwar** [comment]
I'll have a look in the settings tomorrow, but you should be able to open a PR as a random GitHub user.

**Comment by cmbr** [comment]
Upon submission of the pull request, the message I receive is _Pull request creation failed. Validation failed: must be a collaborator_.

**Comment by HLeithner** [comment]
Hi @cmbr based on [SE](https://stackoverflow.com/questions/76462012/pull-request-creation-failed-validation-failed-was-submitted-too-quickly) it seems there is a problem with your account, you might want to contact the github support?

**Comment by alikon** [comment]
i've made #534 following your findings

p.s.
i hope  you'll solve you gh account issue soon

thanks

**Comment by Hackwar** [comment]
Since the PR has been merged, I'm closing this one.
