### ISSUE TITLE
4.0.1 version is pretty old ... maybe new release

### ISSUE THREAD

**Issue by hoochicken** [joomla-extensions/weblinks#538]
### Steps to reproduce the issue

* There is a semicolon after an `endif ?>; `within `mod_weblinks/tmpl/default.php`
* only in install version
* within the current code it looks good

=> seems to me, the Download version is NOT identical with the download version 4.0.1

## Solution
Maybe cast a new release

**Comment by joomdonation** [comment]
Yes. There have been many changes to the code of the extension from the time 4.0.1 released. So Yes, we should have a new release, hopefully together with Joomla 5 releases. We will first have to make sure the extension works with Joomla 5.0 native before making the release.

**Comment by joomdonation** [comment]
Hi @hoochicken

Today, we released version 4.3.0 https://github.com/joomla-extensions/weblinks/releases/tag/4.3.0 which contains code from latest codebase. This issue is now invalid, so I'm closing.
