### ISSUE TITLE
Error in installing weblinks 4.3.1

### ISSUE THREAD

**Issue by rambro** [joomla-extensions/weblinks#541]
### Steps to reproduce the issue
This was my orginial problem on both the test site and real site

Joomla\Filesystem\File::delete: Failed deleting inaccessible file weblinks.php

Package Update: There was an error installing an extension: plg_finder_weblinks.zip

Before updating ensure that the update is compatible with your Joomla! installation.
You are strongly advised to make a backup of your site's files and database before you start updating.

Error updating package.

### Actual result
0 Call to undefined method Joomla\Module\Weblinks\Site\Helper\WeblinksHelper::getWeblinks()

### System information (as much as possible)
php: 8.1.24
joomla 4.4

### Additional comments
I had a problem installing weblinks 4.0.1 to weblinks 4.3.1. I tried to follow the instructions of a similar thread by reinstalling weblinks 4.0.1 then upgrading to 4.3.0, then installing to 4.31. However, did not get that far, because upon resinstalling weblinks 4.0.1 I got and error page when I  clicked my "websites" menu item from the main menu on my site.

website: https://testsitej4.cloudaccess.host/index.php  (this is my test website)

All my data seems to be intact just cannot access my "websites" web page. Any help in this matter would be appreciated.

I also have an override on weblinks extension, because it was producing two columns, so I modified the code to produce one vertical row.

This is my test website. I hope this can be saved, but right now I going down this rabbit hole, hence this new issue

My live site is: https://merrickpost1282.org/index.php

Rick Ambrosino

**Comment by joomdonation** [comment]
Hi Rick

The error you mentioned should not happen for 4.3.1 (It happened for 4.3.0). If you need help with your site, send an email to tuanpn@joomdonation.com give me access to your site. I will help update and make sure it works for you

**Comment by joomdonation** [comment]
@rambro So I received access to your site, and was able to update your site to latest version 4.3.1 without any error. But look like the account was changed, I could not access to https://testsitej4.cloudaccess.host/administrator/ anymore

Could you check that site and let me know if you still need assist ?

**Comment by joomdonation** [comment]
As communicated via email, I was able to update both your test site and your live site to latest version 4.3.1 of weblinks without any errors. So I'm closing this issue.
