### ISSUE TITLE
Joomla 4 and Weblinks 4.3.1

### ISSUE THREAD

**Issue by chriswaterside** [joomla-extensions/weblinks#543]
This is more a question, My Joomla 4 sites are saying I should upgrade to Weblinks 4.3.1
Is Weblinks 4.3.1 compatible with Joomla 4?

**Comment by joomdonation** [comment]
@chriswaterside Yes, it is compatible with Joomla 4.3+. So if your Joomla 4 website is using Joomla 4.3.0 or newer, you can update.

**Comment by chriswaterside** [comment]
Thanks for such a quick reply.
Unfortunately when I try to do an update I get these error messages

Joomla\Filesystem\File::delete: Failed deleting inaccessible file weblinks.php
Package Update: There was an error installing an extension: plg_finder_weblinks.zip
I checked weblinks.php and the permissions looked okay
Joomla! 4.4.0 Stable
PHP 8.1.25

any suggestions?

**Comment by joomdonation** [comment]
That error happens with weblinks 4.3.0 but fixed in 4.3.1. You can follow instructions at https://github.com/joomla-extensions/weblinks/issues/539#issuecomment-1776908394 and it should solve the issue

**Comment by chriswaterside** [comment]
thanks very much, thanks for all your hard work.
