### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by Ricardo12345789** [joomla-extensions/weblinks#546]
![20231129_github_Error Update](https://github.com/joomla-extensions/weblinks/assets/152403927/2815d6d6-d50c-498e-bbf5-fcc5a50a2d28)

Please help me in solving this update problem (see attachment)
Joomla 4.4.1 latest version and everything works fine except this update.

![20231129_github_Error Update](https://github.com/joomla-extensions/weblinks/assets/152403927/95b9893c-7097-4501-8704-c3fc54247c1d)

Kind regards, 
Richard
info@denul.net

**Comment by joomdonation** [comment]
Hello Richard

Please follow the instructions at https://github.com/joomla-extensions/weblinks/issues/539#issuecomment-1776908394 , it should solve your issue

Regards,

Tuan

**Comment by joomdonation** [comment]
Great. Thanks for confirming Richard. I'm closing this issue.

Tuan
