### ISSUE TITLE
Joomla\Filesystem\File::delete: Failed deleting inaccessible file weblinks.php

### ISSUE THREAD

**Issue by diddipoeler** [joomla-extensions/weblinks#547]
### Steps to reproduce the issue
Beim Update der Komponente erhalte ich diesen Fehler.

**Comment by joomdonation** [comment]
Hello

Please see the solution here https://github.com/joomla-extensions/weblinks/issues/539#issuecomment-1776908394

Regards,

Tuan

**Comment by diddipoeler** [comment]
Alles ok.
