### ISSUE TITLE
Call to a member function get() on null

### ISSUE THREAD

**Issue by diddipoeler** [joomla-extensions/weblinks#548]
### Steps to reproduce the issue
JROOT/plugins/search/weblinks/src/Extension/Weblinks.php:106

**Comment by joomdonation** [comment]
@diddipoeler Please use the updated package here https://github.com/joomla-extensions/weblinks/issues/544#issuecomment-1829718417 and let us know if it solves your issue.

**Comment by chmst** [comment]
Closing this - seems to be resolved
