### ISSUE TITLE
Class "Joomla\Plugin\System\Weblinks\Extension\Weblinks" not found 

### ISSUE THREAD

**Issue by LUdo43** [joomla-extensions/weblinks#550]
After upgrading from Weblinks 4.01. to 4.31 I got this error message on the backend and nothing else displayed! Same on the frontend.
Joomla is 4.3.3. and I used the automatic upgrade as displayed in Joomla, php 8.1.27

I tried to manually download Weblinks 4.01, unzipping and transfered the files using ftp, but still teh same issue. Site si not accessible in backend nor frontend.

Any help?

Best regards

Udo

**Comment by LUdo43** [comment]
Joomla is 4.4.3, not 4.3.3

**Comment by joomdonation** [comment]
@LUdo43 Please try to rename the file delete the file administrator/cache/autoload_psr4.php, then try again to see if it helps?

If not, rename the folder plugins/system/weblinks to something else to have the site loads again. Then try to update to update to latest version of weblinks again and let us know if you need more help

**Comment by LUdo43** [comment]
I recreated the site manually by restoring the weblinks-files of v4.01 from teh backup in the directories by using ftp.
Thanks for your help anyway.
Best regards
Udo

**Comment by LUdo43** [comment]
Fixed
