### ISSUE TITLE
Minor error in mod_weblinks

### ISSUE THREAD

**Issue by Pinkeltje** [joomla-extensions/weblinks#551]
### Steps to reproduce the issue
Create module mod_weblinks with multiple categories

### Expected result
Category title only

### Actual result
Category title with ; at the eind

### System information (as much as possible)
Joomla 5.1

### Additional comments
Error in tmpl/default.php on line 55
`        endif; ?>;`
Should be
`        endif; ?>`

**Comment by joomdonation** [comment]
Thanks for reporting the issue @Pinkeltje . It should be fixed with this commit https://github.com/joomla-extensions/weblinks/commit/e2a753828bdb2e19ceb1f474ed7486bcadd2d5ab , so I'm closing this issue.
