### ISSUE TITLE
Improve com_categories markup to locate elements easily 

### ISSUE THREAD

**Issue by javigomez** [joomla-extensions/weblinks#57]
We have issues like this https://github.com/joomla-extensions/weblinks/pull/55/files#r31388936. We need to improve the Joomla admin markup by adding classes that help us to easily locate elements.

**Comment by javigomez** [comment]
related: https://docs.joomla.org/Testing_Joomla_Extensions_with_Codeception#Write_complex_locator_VS._modifying_the_output_of_the_tested_website

**Comment by javigomez** [comment]
a possible solution is sent at https://github.com/joomla-projects/joomla-browser/pull/71/files

**Comment by chrisdavenport** [comment]
Closing as the referenced PR has now been merged.  Thanks @javigomez
