### ISSUE TITLE
Feature Request: Front End User Submission

### ISSUE THREAD

**Issue by GJSchaller** [joomla-extensions/weblinks#69]
Back in the Joomla 1.5 days, I used TEG's Bookmarks component, which had a feature that allowed users to submit new links, which an Admin would then approve (and edit / update / modify, as needed).  I would very much like to see a Submit feature make its way into Weblinks, please.

**Comment by zero-24** [comment]
@GJSchaller We have this already ;) Use the menu item `submit a weblink`. After this you need to set the weblinks `Create` Action to allowed. This should work :smile: 

As this is already implemented i going to close here.
