### ISSUE TITLE
Feature Request: Screenshot / Thumbnail service integration

### ISSUE THREAD

**Issue by GJSchaller** [joomla-extensions/weblinks#70]
Would it be possible to integrate a thumbnail service like ShrinkTheWeb with Weblinks, to auto-generate thumbnails for links?

**Comment by chrisdavenport** [comment]
Whilst that may be possible, it is not something we would support in the official distribution because we wouldn't want to build such a dependence on a third-party service.  Maybe it's an opportunity for a third-party developer to code something that could be added to the JED.
