### ISSUE TITLE
Changes in Joomla Administrator strings needs to be applied to weblinks

### ISSUE THREAD

**Issue by javigomez** [joomla-extensions/weblinks#75]
this pull https://github.com/joomla/joomla-cms/pull/7490 made by @brianteeman brought changes in the administrator interface strings. The same pattern needs to be applied to Weblinks. See:

![capture 2015-07-03 at 13 16 26](https://cloud.githubusercontent.com/assets/1375475/8824108/f17faf6e-3072-11e5-9198-1bcf4cf4508e.png)

![capture 2015-07-03 at 13 16 10](https://cloud.githubusercontent.com/assets/1375475/8824107/f17f50c8-3072-11e5-96b5-40a2ac8eb452.png)

**Comment by brianteeman** [comment]
I will submit a PR here for web links if you want - I didnt touch web links in the core as I wasnt sure how it was working. I guess if I submit a PR here for web links then it can be "backported' to core as we still have the language files in core?

**Comment by javigomez** [comment]
Yup. Thanks. Weblinks was affected partially by some of the changes because weblinks categories use com_categories

**Comment by brianteeman** [comment]
um - is it a known issue that install from web fails on weblinks 
Error
Unable to find install package

**Comment by brianteeman** [comment]
Actually the language issue with categories is NOT with the weblinks component. Unlike all the other core components which have their OWN strings for categories.
com_weblinks uses strings from com_categories.

I can update com_categories in core - I didn't do that originally as it would effect all 3PD that do it that way but I probably should?

**Comment by brianteeman** [comment]
see #76

**Comment by brianteeman** [comment]
Closing as #76 was merged

**Comment by brianteeman** [comment]
Oh oops I dont have the rights to close it on this repo so can someone else please

**Comment by Bakual** [comment]
As you wish :smile:

**Comment by mbabker** [comment]
@brianteeman We have weblinks in the issue tracker (http://issues.joomla.org/tracker/weblinks) so if ACL is correctly set up you'd be able to manage from there.

**Comment by brianteeman** [comment]
@mbabker no I cant - dont worry not really interested in contributing
