### ISSUE TITLE
Trouble updating Joomla weblinks extension in Joomla 3.4.3

### ISSUE THREAD

**Issue by alandarr** [joomla-extensions/weblinks#80]
Site is Joomla 3.4.3 - updated from Joomla 2.x

Tried to install the weblinks extension (through the extension manager) over the currently installed extension resulting in the following messages: (other extension updates have been successful)
______________________
Warning
Error connecting to the server: SSL certificate problem: unable to get local issuer certificate
______________________
Error
Package download failed: https://github.com/joomla-extensions/weblinks/releases/download/3.4.1/pkg_weblinks_3.4.1.zip
______________________

If I were to uninstall the extensions first and upload the zip file to install, I'm not sure which to uninstall since there are several.

![weblinks-extensions](https://cloud.githubusercontent.com/assets/13483933/8875412/11a2ec46-31e7-11e5-9fcc-6c58bbfab813.png)

**Comment by mbabker** [comment]
Please see #79 as this is a duplicate

You don't need to uninstall weblinks first.  You can download the package to your computer and install it using the Install view of the Extension Manager; it will handle detecting an update just fine.
