### ISSUE TITLE
Getting errors using the Joomla extension updater

### ISSUE THREAD

**Issue by cmendla** [joomla-extensions/weblinks#85]
I have encountered the following error with 2 sites.  
- Sites are running the latest Joomla (3.4.3)
- Both sites run admin tools pro firewall (Not sure if that is a factor)

Both get the following error. 

Error
Invalid extension update

Package download failed: https://github.com/joomla-extensions/weblinks/releases/download/3.4.1/pkg_weblinks_3.4.1.zip

**Comment by zero-24** [comment]
Known issue with the SSL Cert of Amazone see: https://github.com/joomla-extensions/weblinks/issues/79

As this is a known issue I going to close here. Thanks for reporting.
