### ISSUE TITLE
Two "images" tabs in Web links

### ISSUE THREAD

**Issue by fontanil** [joomla-extensions/weblinks#89]
Hi,
As an user said today in french Joomla! forum, on Joomla! 3.4.4, web links have two "images" tabs, so adding an image is not possible. I tested and confirm. You can save, but images are not saved: if you edit, all fields remains empty.
![weblinks](https://cloud.githubusercontent.com/assets/8665970/9761390/c31479f6-56fc-11e5-818b-e70f227c9697.jpg)
Thanks for your help!
Robert

**Comment by infograf768** [comment]
I confirm

**Comment by infograf768** [comment]
The solution seems to be adding on top of /administrator/components/com_weblinks/views/weblink/tmpl/edit.php
`$this->ignore_fieldsets = array('images');`

**Comment by fontanil** [comment]
Thanks JM, this corrects perfectly.

**Comment by zero-24** [comment]
closing as we have a PR with the fix by @infograf768 Thanks. https://github.com/joomla-extensions/weblinks/pull/91

**Comment by yorkshireuk** [comment]
The fix by infograf768 worked for me.

Thank you!

**Comment by Maderthaner** [comment]
I have Joomla 3.4.7 and had the same issue. The fix from infograf768 worked for me, too.

Reading the comments, I thought it was fixed in version 3.4.2. Apparently it is not.

**Comment by infograf768** [comment]
weblinks 3.4.2 is apparently not released yet.
