### ISSUE TITLE
Write System Tests to verify Tab Links and Input Fields in Codeception

### ISSUE THREAD

**Issue by puneet0191** [joomla-extensions/weblinks#90]
We need system tests that would verify the tabs present on weblinks extension. to avoid issues like this https://github.com/joomla-extensions/weblinks/issues/89

**Comment by chrisdavenport** [comment]
Closing as this appears to have been at least partially resolved.  Re-open if you think there is anything outstanding.  Thanks @puneet0191

**Comment by puneet0191** [comment]
Thanks @chrisdavenport :smile:
