### ISSUE TITLE
weblinks update having issues

### ISSUE THREAD

**Issue by sbritschgi** [joomla-extensions/weblinks#92]
Hi... ive unzipped package update and individually installed all mods & coms successfully however, keeps reverting back that i have updates for weblinks.... happening to ALL my joomla sites.... please help.... thanks Steve :)

**Comment by zero-24** [comment]
Please use the forums for support: Forum.joomla.org this is the issue Tracker

Some tips:
You need to install the package. As the package gets the update and not the components an modules indivindual.

You Can install the current package over your install if you not hack into the code ;)
