### ISSUE TITLE
Install Joomla in Multilanguage and test Weblinks multilang features

### ISSUE THREAD

**Issue by javigomez** [joomla-extensions/weblinks#95]
Use https://github.com/joomla-projects/joomla-browser/blob/develop/src/JoomlaBrowser.php#L224-L231 instead of installing a normal Joomla.

- [ ] create a translated weblink
- [ ] create a translated category
- [ ] Integration: show in frontend the translations of a weblink and a category

**Comment by infograf768** [comment]
Can you explain better what this issue is about?
Weblinks associations only exist for categories in core. Otherwise core filters weblinks and their categories depending on language.

**Comment by javigomez** [comment]
the task is done here https://github.com/kshitijSharma2014/weblinks/commit/f433aff0a1f5896b24289839b7e4821264c81f24  but needs to wait for this issue to get solved: https://github.com/joomla/joomla-cms/issues/8222

**Comment by chrisdavenport** [comment]
Closing as the referenced issue appears to have been solved.  Feel free to re-open if not.  Thanks @javigomez
